import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'fr' | 'nl' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.services': 'Services',
    'nav.pricing': 'Tarifs',
    'nav.method': 'Méthode & IA',
    'nav.about': 'À propos',
    'nav.contact': 'Contact',
    'nav.audit': 'Audit gratuit',
    
    // Hero
    'hero.title': "L'IT managée.",
    'hero.title2': 'Moderne. Efficace.',
    'hero.subtitle': 'Tekio simplifie et centralise votre IT. C\'est simple, clair, sans prise de tête.',
    'hero.cta1': 'Audit gratuit',
    'hero.cta2': 'Parler à un expert',
    
    // Why Tekio
    'why.title': 'Pourquoi Tekio ?',
    'why.subtitle': 'Une approche moderne de la gestion IT pour les PME.',
    'why.support.title': 'Support rapide',
    'why.support.desc': 'Réponse en moins de 15 minutes. Votre équipe ne reste jamais bloquée.',
    'why.security.title': 'Sécurité 24/7',
    'why.security.desc': 'Monitoring continu et protection proactive de votre infrastructure.',
    'why.automation.title': 'Automatisation & IA',
    'why.automation.desc': 'L\'intelligence artificielle au service de votre productivité.',
    
    // Services
    'services.title': 'Nos services',
    'services.subtitle': 'Tout ce dont votre entreprise a besoin, centralisé.',
    'services.support.title': 'Support & Helpdesk',
    'services.support.desc': 'Assistance technique réactive pour vos équipes.',
    'services.cloud.title': 'Microsoft 365 & Cloud',
    'services.cloud.desc': 'Migration, configuration et gestion de vos outils cloud.',
    'services.security.title': 'Sécurité & Backup',
    'services.security.desc': 'Protection avancée et sauvegarde de vos données.',
    'services.telecom.title': 'Télécom & VoIP',
    'services.telecom.desc': 'Solutions de communication modernes et flexibles.',
    'services.projects.title': 'Projets & Migrations',
    'services.projects.desc': 'Accompagnement sur vos projets de transformation.',
    
    // Technology
    'tech.title': 'Notre technologie',
    'tech.subtitle': 'Des outils modernes pour une IT performante.',
    'tech.ai.title': 'IA intégrée',
    'tech.ai.desc': 'Résolution intelligente des incidents.',
    'tech.automation.title': 'Automatisations',
    'tech.automation.desc': 'Processus optimisés et tâches automatisées.',
    'tech.dashboard.title': 'Dashboards',
    'tech.dashboard.desc': 'Visibilité complète sur votre infrastructure.',
    'tech.reporting.title': 'Reporting clair',
    'tech.reporting.desc': 'Rapports mensuels détaillés et compréhensibles.',
    
    // Pricing
    'pricing.title': 'Nos offres MSP',
    'pricing.subtitle': 'Des formules adaptées à vos besoins.',
    'pricing.setup': 'Setup offert avec contrat 12 mois',
    'pricing.per.user': '/utilisateur/mois',
    'pricing.cta': 'Commencer',
    'pricing.popular': 'Populaire',
    'pricing.bronze.name': 'Bronze',
    'pricing.silver.name': 'Silver',
    'pricing.gold.name': 'Gold',
    'pricing.bronze.price': '29€',
    'pricing.silver.price': '49€',
    'pricing.gold.price': '79€',
    'pricing.feature.support': 'Support helpdesk',
    'pricing.feature.monitoring': 'Monitoring',
    'pricing.feature.backup': 'Backup cloud',
    'pricing.feature.security': 'Sécurité avancée',
    'pricing.feature.m365': 'Gestion Microsoft 365',
    'pricing.feature.voip': 'VoIP inclus',
    'pricing.feature.ai': 'IA & automatisation',
    'pricing.feature.dedicated': 'Ingénieur dédié',
    
    // CTA Final
    'cta.title': 'Faites passer votre IT au niveau supérieur.',
    'cta.subtitle': 'Contactez-nous pour un audit gratuit de votre infrastructure.',
    'cta.button': 'Demander un audit',
    
    // Footer
    'footer.tagline': 'L\'IT managée. Moderne. Efficace.',
    'footer.rights': 'Tous droits réservés.',
    'footer.company': 'Entreprise',
    'footer.legal': 'Mentions légales',
    'footer.privacy': 'Confidentialité',
    
    // About
    'about.title': 'À propos de Tekio',
    'about.mission.title': 'Notre mission',
    'about.mission.desc': 'Simplifier l\'IT des PME pour qu\'elles se concentrent sur leur cœur de métier.',
    'about.vision.title': 'Notre vision',
    'about.vision.desc': 'Devenir le MSP de référence pour les micro-PME grâce à l\'automatisation et l\'IA.',
    'about.founder.title': 'Fondateur',
    'about.founder.name': 'Jawade El Hadouchi',
    'about.founder.desc': 'Plus de 15 ans d\'expérience en IT et infrastructure.',
    'about.values.title': 'Nos valeurs',
    'about.values.simple': 'Simple',
    'about.values.clear': 'Clair',
    'about.values.efficient': 'Efficace',
    
    // Contact
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Une question ? Un projet ? Parlons-en.',
    'contact.name': 'Nom',
    'contact.email': 'Email',
    'contact.company': 'Entreprise',
    'contact.message': 'Message',
    'contact.send': 'Envoyer',
    'contact.info.title': 'Coordonnées',
    'contact.info.address': 'Bruxelles, Belgique',
    
    // Audit
    'audit.title': 'Audit IT gratuit',
    'audit.subtitle': 'Découvrez les points d\'amélioration de votre infrastructure.',
    'audit.benefit1': 'Analyse complète de votre parc',
    'audit.benefit2': 'Identification des risques',
    'audit.benefit3': 'Recommandations personnalisées',
    'audit.benefit4': 'Rapport détaillé offert',
    'audit.cta': 'Demander mon audit',
    
    // Method
    'method.title': 'Notre méthode',
    'method.subtitle': 'Une approche structurée et innovante.',
    'method.itil.title': 'ITIL',
    'method.itil.desc': 'Processus basés sur les meilleures pratiques ITIL.',
    'method.itil.details': 'Gestion des incidents, des changements et des problèmes selon les standards internationaux.',
    'method.automation.title': 'Automatisation',
    'method.automation.desc': 'Tâches répétitives automatisées pour plus d\'efficacité.',
    'method.automation.details': 'Scripts automatisés, déploiements sans intervention, maintenance préventive.',
    'method.ai.title': 'Intelligence artificielle',
    'method.ai.desc': 'IA pour la détection et résolution proactive des incidents.',
    'method.ai.details': 'Analyse prédictive, résolution automatique des incidents récurrents, chatbot intelligent.',
    'method.ai.badge': 'Intelligence Artificielle',
    'method.ai.hero.title': 'L\'IA au service de votre productivité',
    'method.ai.hero.desc': 'Notre plateforme intègre des capacités d\'intelligence artificielle pour anticiper les problèmes, automatiser les tâches répétitives et vous offrir un support toujours plus rapide et pertinent.',
    'method.ai.hero.cta': 'Découvrir nos capacités IA',
    'method.reporting.title': 'Reporting',
    'method.reporting.desc': 'Visibilité totale avec des rapports mensuels clairs.',
    'method.reporting.details': 'Dashboards en temps réel, rapports mensuels détaillés, KPIs personnalisés.',
    
    // Services Details
    'services.detail.support.1': 'Réponse en moins de 15 minutes',
    'services.detail.support.2': 'Support multicanal (téléphone, email, chat)',
    'services.detail.support.3': 'Base de connaissances accessible 24/7',
    'services.detail.support.4': 'Suivi des tickets en temps réel',
    'services.detail.cloud.1': 'Migration Office 365 complète',
    'services.detail.cloud.2': 'Configuration et optimisation',
    'services.detail.cloud.3': 'Formation des utilisateurs',
    'services.detail.cloud.4': 'Gestion des licences',
    'services.detail.security.1': 'Antivirus et anti-malware managé',
    'services.detail.security.2': 'Backup automatisé cloud',
    'services.detail.security.3': 'Test de récupération mensuel',
    'services.detail.security.4': 'Monitoring des menaces 24/7',
    'services.detail.telecom.1': 'Téléphonie VoIP professionnelle',
    'services.detail.telecom.2': 'Intégration Teams / Microsoft',
    'services.detail.telecom.3': 'Numéros locaux et internationaux',
    'services.detail.telecom.4': 'Portabilité garantie',
    'services.detail.projects.1': 'Migration infrastructure complète',
    'services.detail.projects.2': 'Déploiement de nouveaux sites',
    'services.detail.projects.3': 'Audit et conseil technique',
    'services.detail.projects.4': 'Gestion de projet dédiée',
    'services.cta.discover': 'Découvrez tous nos services',
    'services.cta.learn': 'En savoir plus',
    
    // Audit Page
    'audit.free': '100% Gratuit',
    'audit.includes.title': 'Ce que comprend notre audit',
    'audit.process.title': 'Comment ça marche ?',
    'audit.process.step1': 'Remplissez le formulaire',
    'audit.process.step2': 'Nous planifions un appel de 30 min',
    'audit.process.step3': 'Recevez votre rapport personnalisé',
    'audit.form.title': 'Demander mon audit gratuit',
    'audit.form.firstName': 'Prénom',
    'audit.form.lastName': 'Nom',
    'audit.form.email': 'Email professionnel',
    'audit.form.company': 'Entreprise',
    'audit.form.phone': 'Téléphone',
    'audit.form.employees': 'Nombre d\'employés',
    'audit.form.needs': 'Vos besoins principaux',
    'audit.form.placeholder.firstName': 'Jean',
    'audit.form.placeholder.lastName': 'Dupont',
    'audit.form.placeholder.email': 'jean@entreprise.be',
    'audit.form.placeholder.company': 'Nom de votre entreprise',
    'audit.form.placeholder.phone': '+32 XXX XX XX XX',
    'audit.form.placeholder.needs': 'Décrivez brièvement votre situation IT actuelle...',
    'audit.form.select.placeholder': 'Sélectionnez',
    'audit.form.submit.sending': 'Envoi en cours...',
    'audit.form.privacy': 'En soumettant ce formulaire, vous acceptez d\'être contacté par Tekio.',
    'audit.toast.success.title': 'Demande envoyée !',
    'audit.toast.success.desc': 'Nous vous contacterons sous 24h pour planifier votre audit.',
    
    // Pricing Page
    'pricing.plan.bronze.desc': 'Pour les petites équipes qui démarrent',
    'pricing.plan.silver.desc': 'L\'équilibre parfait pour les PME',
    'pricing.plan.gold.desc': 'Service premium tout inclus',
    'pricing.questions.title': 'Des questions sur nos offres ?',
    'pricing.questions.desc': 'Chaque entreprise est unique. Contactez-nous pour une offre personnalisée adaptée à vos besoins.',
    'pricing.dialog.title': 'Demander un devis',
    'pricing.dialog.desc': 'Remplissez ce formulaire et nous vous contacterons avec une offre personnalisée.',
    'pricing.dialog.name': 'Nom',
    'pricing.dialog.email': 'Email',
    'pricing.dialog.company': 'Entreprise',
    'pricing.dialog.employees': 'Nombre d\'utilisateurs',
    'pricing.dialog.message': 'Message (optionnel)',
    'pricing.dialog.placeholder.name': 'Votre nom',
    'pricing.dialog.placeholder.email': 'vous@entreprise.be',
    'pricing.dialog.placeholder.company': 'Nom de votre entreprise',
    'pricing.dialog.placeholder.message': 'Des besoins spécifiques ?',
    'pricing.dialog.submit': 'Envoyer ma demande',
    'pricing.dialog.submit.sending': 'Envoi...',
    'pricing.toast.success.title': 'Demande envoyée !',
    'pricing.toast.success.desc': 'Nous vous contacterons rapidement avec une offre personnalisée.',
    'pricing.interest.prefix': 'Plan intéressé:',
    
    // About Page
    'about.hero.tagline': 'Un MSP moderne basé à Bruxelles, dédié aux micro-PME.',
    'about.founder.quote': 'Mon objectif est simple : offrir aux PME les mêmes outils et le même niveau de service que les grandes entreprises, mais à un prix accessible et avec une approche humaine.',
    'about.cta.ready': 'Prêt à simplifier votre IT ?',
    'about.cta.discuss': 'Parlons de votre projet',
    
    // Contact Page
    'contact.form.placeholder.name': 'John Doe',
    'contact.form.placeholder.email': 'john@company.be',
    'contact.form.placeholder.company': 'Votre entreprise',
    'contact.form.placeholder.message': 'Comment pouvons-nous vous aider ?',
    'contact.form.submit.sending': 'Envoi en cours...',
    'contact.info.address.label': 'Adresse',
    'contact.info.email.label': 'Email',
    'contact.info.phone.label': 'WhatsApp Business',
      'contact.toast.success.title': 'Message envoyé !',
      'contact.toast.success.desc': 'Nous vous répondrons dans les plus brefs délais.',

      // Admin - Leads List
      'admin.leads.title': 'Gestion des Leads',
      'admin.leads.subtitle': 'Tekio Admin',
      'admin.leads.back': 'Retour au site',
      'admin.leads.filter': 'Filtrer par statut',
      'admin.leads.reset': 'Réinitialiser',
      'admin.leads.loading': 'Chargement...',
      'admin.leads.error': 'Erreur lors du chargement des leads',
      'admin.leads.empty': 'Aucun lead trouvé',
      'admin.leads.all': 'Tous les leads',
      'admin.leads.table.date': 'Date',
      'admin.leads.table.company': 'Entreprise',
      'admin.leads.table.contact': 'Contact',
      'admin.leads.table.email': 'Email',
      'admin.leads.table.users': 'Utilisateurs',
      'admin.leads.table.source': 'Source',
      'admin.leads.table.status': 'Statut',
      'admin.leads.table.actions': 'Actions',

      // Admin - Lead Detail
      'admin.lead.back': 'Retour',
      'admin.lead.id': 'Lead #',
      'admin.lead.info': 'Informations du lead',
      'admin.lead.company': 'Entreprise',
      'admin.lead.contact': 'Contact',
      'admin.lead.email': 'Email',
      'admin.lead.phone': 'Téléphone',
      'admin.lead.language': 'Langue',
      'admin.lead.users': 'Nb utilisateurs',
      'admin.lead.created': 'Date de création',
      'admin.lead.source': 'Source',
      'admin.lead.message': 'Message',
      'admin.lead.ai.title': 'Réponse IA suggérée',
      'admin.lead.ai.generate': 'Générer une réponse',
      'admin.lead.ai.generating': 'Génération...',
      'admin.lead.ai.copy': 'Copier la réponse',
      'admin.lead.ai.copied': 'Copié !',
      'admin.lead.ai.empty': 'Cliquez sur "Générer une réponse" pour obtenir une suggestion d\'email personnalisée.',
      'admin.lead.status.title': 'Statut',
      'admin.lead.status.new': 'Nouveau',
      'admin.lead.status.contacted': 'Contacté',
      'admin.lead.status.proposal': 'Proposition',
      'admin.lead.status.won': 'Gagné',
      'admin.lead.status.lost': 'Perdu',
      'admin.lead.notes.title': 'Notes internes',
      'admin.lead.notes.placeholder': 'Ajoutez vos notes ici...',
      'admin.lead.notes.save': 'Sauvegarder',
      'admin.lead.notes.saving': 'Sauvegarde...',
      'admin.lead.actions.title': 'Actions rapides',
      'admin.lead.actions.email': 'Envoyer un email',
      'admin.lead.actions.call': 'Appeler',
      'admin.lead.loading': 'Chargement...',
      'admin.lead.notfound': 'Lead non trouvé',
      'admin.lead.notfound.back': 'Retour à la liste',
      'admin.lead.toast.copied.title': 'Copié !',
      'admin.lead.toast.copied.desc': 'La réponse a été copiée dans le presse-papier.',
      
      // Admin - Sources
      'admin.source.home': 'Accueil',
      'admin.source.audit_page': 'Page Audit',
      'admin.source.contact_page': 'Page Contact',
      'admin.source.pricing_page': 'Page Tarifs',
      
      // Admin - Languages
      'admin.lang.FR': 'Français',
      'admin.lang.NL': 'Nederlands',
      'admin.lang.EN': 'English',
  },
  nl: {
    // Navigation
    'nav.home': 'Home',
    'nav.services': 'Diensten',
    'nav.pricing': 'Prijzen',
    'nav.method': 'Methode & AI',
    'nav.about': 'Over ons',
    'nav.contact': 'Contact',
    'nav.audit': 'Gratis audit',
    
    // Hero
    'hero.title': 'Managed IT.',
    'hero.title2': 'Modern. Efficiënt.',
    'hero.subtitle': 'Tekio vereenvoudigt en centraliseert uw IT. Eenvoudig, duidelijk, zonder gedoe.',
    'hero.cta1': 'Gratis audit',
    'hero.cta2': 'Met een expert spreken',
    
    // Why Tekio
    'why.title': 'Waarom Tekio?',
    'why.subtitle': 'Een moderne aanpak van IT-beheer voor KMO\'s.',
    'why.support.title': 'Snelle support',
    'why.support.desc': 'Reactie binnen 15 minuten. Uw team blijft nooit vastzitten.',
    'why.security.title': 'Beveiliging 24/7',
    'why.security.desc': 'Continue monitoring en proactieve bescherming van uw infrastructuur.',
    'why.automation.title': 'Automatisering & AI',
    'why.automation.desc': 'Kunstmatige intelligentie ten dienste van uw productiviteit.',
    
    // Services
    'services.title': 'Onze diensten',
    'services.subtitle': 'Alles wat uw bedrijf nodig heeft, gecentraliseerd.',
    'services.support.title': 'Support & Helpdesk',
    'services.support.desc': 'Reactieve technische ondersteuning voor uw teams.',
    'services.cloud.title': 'Microsoft 365 & Cloud',
    'services.cloud.desc': 'Migratie, configuratie en beheer van uw cloud-tools.',
    'services.security.title': 'Beveiliging & Backup',
    'services.security.desc': 'Geavanceerde bescherming en back-up van uw gegevens.',
    'services.telecom.title': 'Telecom & VoIP',
    'services.telecom.desc': 'Moderne en flexibele communicatieoplossingen.',
    'services.projects.title': 'Projecten & Migraties',
    'services.projects.desc': 'Begeleiding bij uw transformatieprojecten.',
    
    // Technology
    'tech.title': 'Onze technologie',
    'tech.subtitle': 'Moderne tools voor performante IT.',
    'tech.ai.title': 'Geïntegreerde AI',
    'tech.ai.desc': 'Intelligente incidentoplossing.',
    'tech.automation.title': 'Automatiseringen',
    'tech.automation.desc': 'Geoptimaliseerde processen en geautomatiseerde taken.',
    'tech.dashboard.title': 'Dashboards',
    'tech.dashboard.desc': 'Volledige zichtbaarheid op uw infrastructuur.',
    'tech.reporting.title': 'Duidelijke rapportage',
    'tech.reporting.desc': 'Gedetailleerde en begrijpelijke maandelijkse rapporten.',
    
    // Pricing
    'pricing.title': 'Onze MSP-aanbiedingen',
    'pricing.subtitle': 'Formules aangepast aan uw behoeften.',
    'pricing.setup': 'Setup gratis bij 12-maanden contract',
    'pricing.per.user': '/gebruiker/maand',
    'pricing.cta': 'Starten',
    'pricing.popular': 'Populair',
    'pricing.bronze.name': 'Bronze',
    'pricing.silver.name': 'Silver',
    'pricing.gold.name': 'Gold',
    'pricing.bronze.price': '29€',
    'pricing.silver.price': '49€',
    'pricing.gold.price': '79€',
    'pricing.feature.support': 'Helpdesk support',
    'pricing.feature.monitoring': 'Monitoring',
    'pricing.feature.backup': 'Cloud backup',
    'pricing.feature.security': 'Geavanceerde beveiliging',
    'pricing.feature.m365': 'Microsoft 365 beheer',
    'pricing.feature.voip': 'VoIP inbegrepen',
    'pricing.feature.ai': 'AI & automatisering',
    'pricing.feature.dedicated': 'Toegewijde engineer',
    
    // CTA Final
    'cta.title': 'Breng uw IT naar het volgende niveau.',
    'cta.subtitle': 'Neem contact met ons op voor een gratis audit van uw infrastructuur.',
    'cta.button': 'Audit aanvragen',
    
    // Footer
    'footer.tagline': 'Managed IT. Modern. Efficiënt.',
    'footer.rights': 'Alle rechten voorbehouden.',
    'footer.company': 'Bedrijf',
    'footer.legal': 'Juridische informatie',
    'footer.privacy': 'Privacy',
    
    // About
    'about.title': 'Over Tekio',
    'about.mission.title': 'Onze missie',
    'about.mission.desc': 'De IT van KMO\'s vereenvoudigen zodat zij zich kunnen concentreren op hun kernactiviteit.',
    'about.vision.title': 'Onze visie',
    'about.vision.desc': 'De referentie MSP worden voor micro-KMO\'s dankzij automatisering en AI.',
    'about.founder.title': 'Oprichter',
    'about.founder.name': 'Jawade El Hadouchi',
    'about.founder.desc': 'Meer dan 15 jaar ervaring in IT en infrastructuur.',
    'about.values.title': 'Onze waarden',
    'about.values.simple': 'Eenvoudig',
    'about.values.clear': 'Duidelijk',
    'about.values.efficient': 'Efficiënt',
    
    // Contact
    'contact.title': 'Contacteer ons',
    'contact.subtitle': 'Een vraag? Een project? Laten we praten.',
    'contact.name': 'Naam',
    'contact.email': 'E-mail',
    'contact.company': 'Bedrijf',
    'contact.message': 'Bericht',
    'contact.send': 'Verzenden',
    'contact.info.title': 'Contactgegevens',
    'contact.info.address': 'Brussel, België',
    
    // Audit
    'audit.title': 'Gratis IT-audit',
    'audit.subtitle': 'Ontdek de verbeterpunten van uw infrastructuur.',
    'audit.benefit1': 'Volledige analyse van uw IT-park',
    'audit.benefit2': 'Identificatie van risico\'s',
    'audit.benefit3': 'Gepersonaliseerde aanbevelingen',
    'audit.benefit4': 'Gedetailleerd rapport gratis',
    'audit.cta': 'Mijn audit aanvragen',
    
    // Method
    'method.title': 'Onze methode',
    'method.subtitle': 'Een gestructureerde en innovatieve aanpak.',
    'method.itil.title': 'ITIL',
    'method.itil.desc': 'Processen gebaseerd op ITIL best practices.',
    'method.itil.details': 'Beheer van incidenten, wijzigingen en problemen volgens internationale normen.',
    'method.automation.title': 'Automatisering',
    'method.automation.desc': 'Geautomatiseerde repetitieve taken voor meer efficiëntie.',
    'method.automation.details': 'Geautomatiseerde scripts, implementaties zonder interventie, preventief onderhoud.',
    'method.ai.title': 'Kunstmatige intelligentie',
    'method.ai.desc': 'AI voor proactieve detectie en oplossing van incidenten.',
    'method.ai.details': 'Voorspellende analyse, automatische oplossing van terugkerende incidenten, intelligente chatbot.',
    'method.ai.badge': 'Kunstmatige Intelligentie',
    'method.ai.hero.title': 'AI ten dienste van uw productiviteit',
    'method.ai.hero.desc': 'Ons platform integreert kunstmatige intelligentie-mogelijkheden om problemen te anticiperen, repetitieve taken te automatiseren en u altijd snellere en relevantere ondersteuning te bieden.',
    'method.ai.hero.cta': 'Ontdek onze AI-mogelijkheden',
    'method.reporting.title': 'Rapportage',
    'method.reporting.desc': 'Totale zichtbaarheid met duidelijke maandelijkse rapporten.',
    'method.reporting.details': 'Real-time dashboards, gedetailleerde maandelijkse rapporten, gepersonaliseerde KPI\'s.',
    
    // Services Details
    'services.detail.support.1': 'Reactie binnen 15 minuten',
    'services.detail.support.2': 'Multi-channel support (telefoon, e-mail, chat)',
    'services.detail.support.3': 'Kennisbank 24/7 toegankelijk',
    'services.detail.support.4': 'Real-time ticketopvolging',
    'services.detail.cloud.1': 'Volledige Office 365-migratie',
    'services.detail.cloud.2': 'Configuratie en optimalisatie',
    'services.detail.cloud.3': 'Gebruikerstraining',
    'services.detail.cloud.4': 'Licentiebeheer',
    'services.detail.security.1': 'Beheerde antivirus en anti-malware',
    'services.detail.security.2': 'Geautomatiseerde cloud backup',
    'services.detail.security.3': 'Maandelijkse hersteltest',
    'services.detail.security.4': '24/7 dreigingsbewaking',
    'services.detail.telecom.1': 'Professionele VoIP-telefonie',
    'services.detail.telecom.2': 'Teams / Microsoft-integratie',
    'services.detail.telecom.3': 'Lokale en internationale nummers',
    'services.detail.telecom.4': 'Gegarandeerde portabiliteit',
    'services.detail.projects.1': 'Volledige infrastructuurmigratie',
    'services.detail.projects.2': 'Uitrol van nieuwe sites',
    'services.detail.projects.3': 'Audit en technisch advies',
    'services.detail.projects.4': 'Toegewijd projectbeheer',
    'services.cta.discover': 'Ontdek al onze diensten',
    'services.cta.learn': 'Meer weten',
    
    // Audit Page
    'audit.free': '100% Gratis',
    'audit.includes.title': 'Wat onze audit omvat',
    'audit.process.title': 'Hoe werkt het?',
    'audit.process.step1': 'Vul het formulier in',
    'audit.process.step2': 'We plannen een gesprek van 30 min',
    'audit.process.step3': 'Ontvang uw gepersonaliseerd rapport',
    'audit.form.title': 'Vraag mijn gratis audit aan',
    'audit.form.firstName': 'Voornaam',
    'audit.form.lastName': 'Achternaam',
    'audit.form.email': 'Professionele e-mail',
    'audit.form.company': 'Bedrijf',
    'audit.form.phone': 'Telefoon',
    'audit.form.employees': 'Aantal werknemers',
    'audit.form.needs': 'Uw belangrijkste behoeften',
    'audit.form.placeholder.firstName': 'Jan',
    'audit.form.placeholder.lastName': 'Janssen',
    'audit.form.placeholder.email': 'jan@bedrijf.be',
    'audit.form.placeholder.company': 'Naam van uw bedrijf',
    'audit.form.placeholder.phone': '+32 XXX XX XX XX',
    'audit.form.placeholder.needs': 'Beschrijf kort uw huidige IT-situatie...',
    'audit.form.select.placeholder': 'Selecteer',
    'audit.form.submit.sending': 'Verzenden...',
    'audit.form.privacy': 'Door dit formulier in te dienen, gaat u ermee akkoord te worden gecontacteerd door Tekio.',
    'audit.toast.success.title': 'Aanvraag verzonden!',
    'audit.toast.success.desc': 'We nemen binnen 24 uur contact met u op om uw audit te plannen.',
    
    // Pricing Page
    'pricing.plan.bronze.desc': 'Voor kleine teams die starten',
    'pricing.plan.silver.desc': 'De perfecte balans voor KMO\'s',
    'pricing.plan.gold.desc': 'Premium all-inclusive service',
    'pricing.questions.title': 'Vragen over onze aanbiedingen?',
    'pricing.questions.desc': 'Elk bedrijf is uniek. Neem contact met ons op voor een gepersonaliseerd aanbod aangepast aan uw behoeften.',
    'pricing.dialog.title': 'Een offerte aanvragen',
    'pricing.dialog.desc': 'Vul dit formulier in en we nemen contact met u op met een gepersonaliseerd aanbod.',
    'pricing.dialog.name': 'Naam',
    'pricing.dialog.email': 'E-mail',
    'pricing.dialog.company': 'Bedrijf',
    'pricing.dialog.employees': 'Aantal gebruikers',
    'pricing.dialog.message': 'Bericht (optioneel)',
    'pricing.dialog.placeholder.name': 'Uw naam',
    'pricing.dialog.placeholder.email': 'u@bedrijf.be',
    'pricing.dialog.placeholder.company': 'Naam van uw bedrijf',
    'pricing.dialog.placeholder.message': 'Specifieke behoeften?',
    'pricing.dialog.submit': 'Mijn aanvraag verzenden',
    'pricing.dialog.submit.sending': 'Verzenden...',
    'pricing.toast.success.title': 'Aanvraag verzonden!',
    'pricing.toast.success.desc': 'We nemen snel contact met u op met een gepersonaliseerd aanbod.',
    'pricing.interest.prefix': 'Interessant plan:',
    
    // About Page
    'about.hero.tagline': 'Een moderne MSP gevestigd in Brussel, toegewijd aan micro-KMO\'s.',
    'about.founder.quote': 'Mijn doel is eenvoudig: KMO\'s dezelfde tools en hetzelfde serviceniveau bieden als grote bedrijven, maar tegen een betaalbare prijs en met een menselijke aanpak.',
    'about.cta.ready': 'Klaar om uw IT te vereenvoudigen?',
    'about.cta.discuss': 'Laten we over uw project praten',
    
    // Contact Page
    'contact.form.placeholder.name': 'John Doe',
    'contact.form.placeholder.email': 'john@bedrijf.be',
    'contact.form.placeholder.company': 'Uw bedrijf',
    'contact.form.placeholder.message': 'Hoe kunnen we u helpen?',
    'contact.form.submit.sending': 'Verzenden...',
    'contact.info.address.label': 'Adres',
    'contact.info.email.label': 'E-mail',
    'contact.info.phone.label': 'WhatsApp Business',
      'contact.toast.success.title': 'Bericht verzonden!',
      'contact.toast.success.desc': 'We nemen zo snel mogelijk contact met u op.',

      // Admin - Leads List
      'admin.leads.title': 'Leadbeheer',
      'admin.leads.subtitle': 'Tekio Admin',
      'admin.leads.back': 'Terug naar site',
      'admin.leads.filter': 'Filteren op status',
      'admin.leads.reset': 'Reset',
      'admin.leads.loading': 'Laden...',
      'admin.leads.error': 'Fout bij het laden van leads',
      'admin.leads.empty': 'Geen leads gevonden',
      'admin.leads.all': 'Alle leads',
      'admin.leads.table.date': 'Datum',
      'admin.leads.table.company': 'Bedrijf',
      'admin.leads.table.contact': 'Contact',
      'admin.leads.table.email': 'E-mail',
      'admin.leads.table.users': 'Gebruikers',
      'admin.leads.table.source': 'Bron',
      'admin.leads.table.status': 'Status',
      'admin.leads.table.actions': 'Acties',

      // Admin - Lead Detail
      'admin.lead.back': 'Terug',
      'admin.lead.id': 'Lead #',
      'admin.lead.info': 'Leadinformatie',
      'admin.lead.company': 'Bedrijf',
      'admin.lead.contact': 'Contact',
      'admin.lead.email': 'E-mail',
      'admin.lead.phone': 'Telefoon',
      'admin.lead.language': 'Taal',
      'admin.lead.users': 'Aantal gebruikers',
      'admin.lead.created': 'Aanmaakdatum',
      'admin.lead.source': 'Bron',
      'admin.lead.message': 'Bericht',
      'admin.lead.ai.title': 'AI-antwoordsuggestie',
      'admin.lead.ai.generate': 'Antwoord genereren',
      'admin.lead.ai.generating': 'Genereren...',
      'admin.lead.ai.copy': 'Antwoord kopiëren',
      'admin.lead.ai.copied': 'Gekopieerd!',
      'admin.lead.ai.empty': 'Klik op "Antwoord genereren" om een gepersonaliseerde e-mailsuggestie te krijgen.',
      'admin.lead.status.title': 'Status',
      'admin.lead.status.new': 'Nieuw',
      'admin.lead.status.contacted': 'Gecontacteerd',
      'admin.lead.status.proposal': 'Voorstel',
      'admin.lead.status.won': 'Gewonnen',
      'admin.lead.status.lost': 'Verloren',
      'admin.lead.notes.title': 'Interne notities',
      'admin.lead.notes.placeholder': 'Voeg hier uw notities toe...',
      'admin.lead.notes.save': 'Opslaan',
      'admin.lead.notes.saving': 'Opslaan...',
      'admin.lead.actions.title': 'Snelle acties',
      'admin.lead.actions.email': 'E-mail verzenden',
      'admin.lead.actions.call': 'Bellen',
      'admin.lead.loading': 'Laden...',
      'admin.lead.notfound': 'Lead niet gevonden',
      'admin.lead.notfound.back': 'Terug naar lijst',
      'admin.lead.toast.copied.title': 'Gekopieerd!',
      'admin.lead.toast.copied.desc': 'Het antwoord is naar het klembord gekopieerd.',
      
      // Admin - Sources
      'admin.source.home': 'Home',
      'admin.source.audit_page': 'Auditpagina',
      'admin.source.contact_page': 'Contactpagina',
      'admin.source.pricing_page': 'Prijzenpagina',
      
      // Admin - Languages
      'admin.lang.FR': 'Frans',
      'admin.lang.NL': 'Nederlands',
      'admin.lang.EN': 'Engels',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.pricing': 'Pricing',
    'nav.method': 'Method & AI',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.audit': 'Free audit',
    
    // Hero
    'hero.title': 'Managed IT.',
    'hero.title2': 'Modern. Efficient.',
    'hero.subtitle': 'Tekio simplifies and centralizes your IT. Simple, clear, hassle-free.',
    'hero.cta1': 'Free audit',
    'hero.cta2': 'Talk to an expert',
    
    // Why Tekio
    'why.title': 'Why Tekio?',
    'why.subtitle': 'A modern approach to IT management for SMEs.',
    'why.support.title': 'Fast support',
    'why.support.desc': 'Response within 15 minutes. Your team never stays stuck.',
    'why.security.title': '24/7 Security',
    'why.security.desc': 'Continuous monitoring and proactive protection of your infrastructure.',
    'why.automation.title': 'Automation & AI',
    'why.automation.desc': 'Artificial intelligence at the service of your productivity.',
    
    // Services
    'services.title': 'Our services',
    'services.subtitle': 'Everything your business needs, centralized.',
    'services.support.title': 'Support & Helpdesk',
    'services.support.desc': 'Responsive technical support for your teams.',
    'services.cloud.title': 'Microsoft 365 & Cloud',
    'services.cloud.desc': 'Migration, configuration and management of your cloud tools.',
    'services.security.title': 'Security & Backup',
    'services.security.desc': 'Advanced protection and backup of your data.',
    'services.telecom.title': 'Telecom & VoIP',
    'services.telecom.desc': 'Modern and flexible communication solutions.',
    'services.projects.title': 'Projects & Migrations',
    'services.projects.desc': 'Support for your transformation projects.',
    
    // Technology
    'tech.title': 'Our technology',
    'tech.subtitle': 'Modern tools for efficient IT.',
    'tech.ai.title': 'Integrated AI',
    'tech.ai.desc': 'Intelligent incident resolution.',
    'tech.automation.title': 'Automations',
    'tech.automation.desc': 'Optimized processes and automated tasks.',
    'tech.dashboard.title': 'Dashboards',
    'tech.dashboard.desc': 'Complete visibility of your infrastructure.',
    'tech.reporting.title': 'Clear reporting',
    'tech.reporting.desc': 'Detailed and understandable monthly reports.',
    
    // Pricing
    'pricing.title': 'Our MSP plans',
    'pricing.subtitle': 'Plans tailored to your needs.',
    'pricing.setup': 'Free setup with 12-month contract',
    'pricing.per.user': '/user/month',
    'pricing.cta': 'Get started',
    'pricing.popular': 'Popular',
    'pricing.bronze.name': 'Bronze',
    'pricing.silver.name': 'Silver',
    'pricing.gold.name': 'Gold',
    'pricing.bronze.price': '€29',
    'pricing.silver.price': '€49',
    'pricing.gold.price': '€79',
    'pricing.feature.support': 'Helpdesk support',
    'pricing.feature.monitoring': 'Monitoring',
    'pricing.feature.backup': 'Cloud backup',
    'pricing.feature.security': 'Advanced security',
    'pricing.feature.m365': 'Microsoft 365 management',
    'pricing.feature.voip': 'VoIP included',
    'pricing.feature.ai': 'AI & automation',
    'pricing.feature.dedicated': 'Dedicated engineer',
    
    // CTA Final
    'cta.title': 'Take your IT to the next level.',
    'cta.subtitle': 'Contact us for a free audit of your infrastructure.',
    'cta.button': 'Request an audit',
    
    // Footer
    'footer.tagline': 'Managed IT. Modern. Efficient.',
    'footer.rights': 'All rights reserved.',
    'footer.company': 'Company',
    'footer.legal': 'Legal notice',
    'footer.privacy': 'Privacy',
    
    // About
    'about.title': 'About Tekio',
    'about.mission.title': 'Our mission',
    'about.mission.desc': 'Simplify IT for SMEs so they can focus on their core business.',
    'about.vision.title': 'Our vision',
    'about.vision.desc': 'Become the reference MSP for micro-SMEs through automation and AI.',
    'about.founder.title': 'Founder',
    'about.founder.name': 'Jawade El Hadouchi',
    'about.founder.desc': 'Over 15 years of experience in IT and infrastructure.',
    'about.values.title': 'Our values',
    'about.values.simple': 'Simple',
    'about.values.clear': 'Clear',
    'about.values.efficient': 'Efficient',
    
    // Contact
    'contact.title': 'Contact us',
    'contact.subtitle': 'A question? A project? Let\'s talk.',
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.company': 'Company',
    'contact.message': 'Message',
    'contact.send': 'Send',
    'contact.info.title': 'Contact details',
    'contact.info.address': 'Brussels, Belgium',
    
    // Audit
    'audit.title': 'Free IT audit',
    'audit.subtitle': 'Discover the improvement areas of your infrastructure.',
    'audit.benefit1': 'Complete analysis of your IT assets',
    'audit.benefit2': 'Risk identification',
    'audit.benefit3': 'Personalized recommendations',
    'audit.benefit4': 'Detailed report included',
    'audit.cta': 'Request my audit',
    
    // Method
    'method.title': 'Our method',
    'method.subtitle': 'A structured and innovative approach.',
    'method.itil.title': 'ITIL',
    'method.itil.desc': 'Processes based on ITIL best practices.',
    'method.itil.details': 'Incident, change and problem management according to international standards.',
    'method.automation.title': 'Automation',
    'method.automation.desc': 'Automated repetitive tasks for more efficiency.',
    'method.automation.details': 'Automated scripts, deployments without intervention, preventive maintenance.',
    'method.ai.title': 'Artificial intelligence',
    'method.ai.desc': 'AI for proactive detection and resolution of incidents.',
    'method.ai.details': 'Predictive analysis, automatic resolution of recurring incidents, intelligent chatbot.',
    'method.ai.badge': 'Artificial Intelligence',
    'method.ai.hero.title': 'AI at the service of your productivity',
    'method.ai.hero.desc': 'Our platform integrates artificial intelligence capabilities to anticipate problems, automate repetitive tasks and offer you ever faster and more relevant support.',
    'method.ai.hero.cta': 'Discover our AI capabilities',
    'method.reporting.title': 'Reporting',
    'method.reporting.desc': 'Total visibility with clear monthly reports.',
    'method.reporting.details': 'Real-time dashboards, detailed monthly reports, customized KPIs.',
    
    // Services Details
    'services.detail.support.1': 'Response within 15 minutes',
    'services.detail.support.2': 'Multi-channel support (phone, email, chat)',
    'services.detail.support.3': '24/7 accessible knowledge base',
    'services.detail.support.4': 'Real-time ticket tracking',
    'services.detail.cloud.1': 'Complete Office 365 migration',
    'services.detail.cloud.2': 'Configuration and optimization',
    'services.detail.cloud.3': 'User training',
    'services.detail.cloud.4': 'License management',
    'services.detail.security.1': 'Managed antivirus and anti-malware',
    'services.detail.security.2': 'Automated cloud backup',
    'services.detail.security.3': 'Monthly recovery test',
    'services.detail.security.4': '24/7 threat monitoring',
    'services.detail.telecom.1': 'Professional VoIP telephony',
    'services.detail.telecom.2': 'Teams / Microsoft integration',
    'services.detail.telecom.3': 'Local and international numbers',
    'services.detail.telecom.4': 'Guaranteed portability',
    'services.detail.projects.1': 'Complete infrastructure migration',
    'services.detail.projects.2': 'Deployment of new sites',
    'services.detail.projects.3': 'Audit and technical advice',
    'services.detail.projects.4': 'Dedicated project management',
    'services.cta.discover': 'Discover all our services',
    'services.cta.learn': 'Learn more',
    
    // Audit Page
    'audit.free': '100% Free',
    'audit.includes.title': 'What our audit includes',
    'audit.process.title': 'How does it work?',
    'audit.process.step1': 'Fill out the form',
    'audit.process.step2': 'We schedule a 30-min call',
    'audit.process.step3': 'Receive your personalized report',
    'audit.form.title': 'Request my free audit',
    'audit.form.firstName': 'First name',
    'audit.form.lastName': 'Last name',
    'audit.form.email': 'Professional email',
    'audit.form.company': 'Company',
    'audit.form.phone': 'Phone',
    'audit.form.employees': 'Number of employees',
    'audit.form.needs': 'Your main needs',
    'audit.form.placeholder.firstName': 'John',
    'audit.form.placeholder.lastName': 'Doe',
    'audit.form.placeholder.email': 'john@company.be',
    'audit.form.placeholder.company': 'Your company name',
    'audit.form.placeholder.phone': '+32 XXX XX XX XX',
    'audit.form.placeholder.needs': 'Briefly describe your current IT situation...',
    'audit.form.select.placeholder': 'Select',
    'audit.form.submit.sending': 'Sending...',
    'audit.form.privacy': 'By submitting this form, you agree to be contacted by Tekio.',
    'audit.toast.success.title': 'Request sent!',
    'audit.toast.success.desc': 'We will contact you within 24h to schedule your audit.',
    
    // Pricing Page
    'pricing.plan.bronze.desc': 'For small teams getting started',
    'pricing.plan.silver.desc': 'The perfect balance for SMEs',
    'pricing.plan.gold.desc': 'All-inclusive premium service',
    'pricing.questions.title': 'Questions about our offers?',
    'pricing.questions.desc': 'Every business is unique. Contact us for a personalized offer tailored to your needs.',
    'pricing.dialog.title': 'Request a quote',
    'pricing.dialog.desc': 'Fill in this form and we will contact you with a personalized offer.',
    'pricing.dialog.name': 'Name',
    'pricing.dialog.email': 'Email',
    'pricing.dialog.company': 'Company',
    'pricing.dialog.employees': 'Number of users',
    'pricing.dialog.message': 'Message (optional)',
    'pricing.dialog.placeholder.name': 'Your name',
    'pricing.dialog.placeholder.email': 'you@company.be',
    'pricing.dialog.placeholder.company': 'Your company name',
    'pricing.dialog.placeholder.message': 'Specific needs?',
    'pricing.dialog.submit': 'Send my request',
    'pricing.dialog.submit.sending': 'Sending...',
    'pricing.toast.success.title': 'Request sent!',
    'pricing.toast.success.desc': 'We will contact you shortly with a personalized offer.',
    'pricing.interest.prefix': 'Interested plan:',
    
    // About Page
    'about.hero.tagline': 'A modern MSP based in Brussels, dedicated to micro-SMEs.',
    'about.founder.quote': 'My goal is simple: offer SMEs the same tools and the same level of service as large companies, but at an affordable price and with a human approach.',
    'about.cta.ready': 'Ready to simplify your IT?',
    'about.cta.discuss': 'Let\'s talk about your project',
    
    // Contact Page
    'contact.form.placeholder.name': 'John Doe',
    'contact.form.placeholder.email': 'john@company.be',
    'contact.form.placeholder.company': 'Your company',
    'contact.form.placeholder.message': 'How can we help you?',
    'contact.form.submit.sending': 'Sending...',
    'contact.info.address.label': 'Address',
    'contact.info.email.label': 'Email',
    'contact.info.phone.label': 'WhatsApp Business',
      'contact.toast.success.title': 'Message sent!',
      'contact.toast.success.desc': 'We will respond as soon as possible.',

      // Admin - Leads List
      'admin.leads.title': 'Lead Management',
      'admin.leads.subtitle': 'Tekio Admin',
      'admin.leads.back': 'Back to site',
      'admin.leads.filter': 'Filter by status',
      'admin.leads.reset': 'Reset',
      'admin.leads.loading': 'Loading...',
      'admin.leads.error': 'Error loading leads',
      'admin.leads.empty': 'No leads found',
      'admin.leads.all': 'All leads',
      'admin.leads.table.date': 'Date',
      'admin.leads.table.company': 'Company',
      'admin.leads.table.contact': 'Contact',
      'admin.leads.table.email': 'Email',
      'admin.leads.table.users': 'Users',
      'admin.leads.table.source': 'Source',
      'admin.leads.table.status': 'Status',
      'admin.leads.table.actions': 'Actions',

      // Admin - Lead Detail
      'admin.lead.back': 'Back',
      'admin.lead.id': 'Lead #',
      'admin.lead.info': 'Lead information',
      'admin.lead.company': 'Company',
      'admin.lead.contact': 'Contact',
      'admin.lead.email': 'Email',
      'admin.lead.phone': 'Phone',
      'admin.lead.language': 'Language',
      'admin.lead.users': 'Number of users',
      'admin.lead.created': 'Creation date',
      'admin.lead.source': 'Source',
      'admin.lead.message': 'Message',
      'admin.lead.ai.title': 'AI suggested reply',
      'admin.lead.ai.generate': 'Generate reply',
      'admin.lead.ai.generating': 'Generating...',
      'admin.lead.ai.copy': 'Copy reply',
      'admin.lead.ai.copied': 'Copied!',
      'admin.lead.ai.empty': 'Click "Generate reply" to get a personalized email suggestion.',
      'admin.lead.status.title': 'Status',
      'admin.lead.status.new': 'New',
      'admin.lead.status.contacted': 'Contacted',
      'admin.lead.status.proposal': 'Proposal',
      'admin.lead.status.won': 'Won',
      'admin.lead.status.lost': 'Lost',
      'admin.lead.notes.title': 'Internal notes',
      'admin.lead.notes.placeholder': 'Add your notes here...',
      'admin.lead.notes.save': 'Save',
      'admin.lead.notes.saving': 'Saving...',
      'admin.lead.actions.title': 'Quick actions',
      'admin.lead.actions.email': 'Send email',
      'admin.lead.actions.call': 'Call',
      'admin.lead.loading': 'Loading...',
      'admin.lead.notfound': 'Lead not found',
      'admin.lead.notfound.back': 'Back to list',
      'admin.lead.toast.copied.title': 'Copied!',
      'admin.lead.toast.copied.desc': 'The reply has been copied to the clipboard.',
      
      // Admin - Sources
      'admin.source.home': 'Home',
      'admin.source.audit_page': 'Audit Page',
      'admin.source.contact_page': 'Contact Page',
      'admin.source.pricing_page': 'Pricing Page',
      
      // Admin - Languages
      'admin.lang.FR': 'French',
      'admin.lang.NL': 'Dutch',
      'admin.lang.EN': 'English',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
