import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'fr' | 'nl' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.services': 'Services',
    'nav.pricing': 'Tarifs',
    'nav.method': 'Méthode & IA',
    'nav.about': 'À propos',
    'nav.contact': 'Contact',
    'nav.audit': 'Audit gratuit',
    
    // Hero
    'hero.title': "L'IT managée.",
    'hero.title2': 'Moderne. Efficace.',
    'hero.subtitle': 'Tekio simplifie et centralise votre IT. C\'est simple, clair, sans prise de tête.',
    'hero.cta1': 'Audit gratuit',
    'hero.cta2': 'Parler à un expert',
    
    // Why Tekio
    'why.title': 'Pourquoi Tekio ?',
    'why.subtitle': 'Une approche moderne de la gestion IT pour les PME.',
    'why.support.title': 'Support rapide',
    'why.support.desc': 'Réponse en moins de 15 minutes. Votre équipe ne reste jamais bloquée.',
    'why.security.title': 'Sécurité 24/7',
    'why.security.desc': 'Monitoring continu et protection proactive de votre infrastructure.',
    'why.automation.title': 'Automatisation & IA',
    'why.automation.desc': 'L\'intelligence artificielle au service de votre productivité.',
    
    // Services
    'services.title': 'Nos services',
    'services.subtitle': 'Tout ce dont votre entreprise a besoin, centralisé.',
    'services.support.title': 'Support & Helpdesk',
    'services.support.desc': 'Assistance technique réactive pour vos équipes.',
    'services.cloud.title': 'Microsoft 365 & Cloud',
    'services.cloud.desc': 'Migration, configuration et gestion de vos outils cloud.',
    'services.security.title': 'Sécurité & Backup',
    'services.security.desc': 'Protection avancée et sauvegarde de vos données.',
    'services.telecom.title': 'Télécom & VoIP',
    'services.telecom.desc': 'Solutions de communication modernes et flexibles.',
    'services.projects.title': 'Projets & Migrations',
    'services.projects.desc': 'Accompagnement sur vos projets de transformation.',
    
    // Technology
    'tech.title': 'Notre technologie',
    'tech.subtitle': 'Des outils modernes pour une IT performante.',
    'tech.ai.title': 'IA intégrée',
    'tech.ai.desc': 'Résolution intelligente des incidents.',
    'tech.automation.title': 'Automatisations',
    'tech.automation.desc': 'Processus optimisés et tâches automatisées.',
    'tech.dashboard.title': 'Dashboards',
    'tech.dashboard.desc': 'Visibilité complète sur votre infrastructure.',
    'tech.reporting.title': 'Reporting clair',
    'tech.reporting.desc': 'Rapports mensuels détaillés et compréhensibles.',
    
    // Pricing
    'pricing.title': 'Nos offres MSP',
    'pricing.subtitle': 'Des formules adaptées à vos besoins.',
    'pricing.setup': 'Setup offert avec contrat 12 mois',
    'pricing.per.user': '/utilisateur/mois',
    'pricing.cta': 'Commencer',
    'pricing.popular': 'Populaire',
    'pricing.bronze.name': 'Bronze',
    'pricing.silver.name': 'Silver',
    'pricing.gold.name': 'Gold',
    'pricing.bronze.price': '29€',
    'pricing.silver.price': '49€',
    'pricing.gold.price': '79€',
    'pricing.feature.support': 'Support helpdesk',
    'pricing.feature.monitoring': 'Monitoring',
    'pricing.feature.backup': 'Backup cloud',
    'pricing.feature.security': 'Sécurité avancée',
    'pricing.feature.m365': 'Gestion Microsoft 365',
    'pricing.feature.voip': 'VoIP inclus',
    'pricing.feature.ai': 'IA & automatisation',
    'pricing.feature.dedicated': 'Ingénieur dédié',
    
    // CTA Final
    'cta.title': 'Faites passer votre IT au niveau supérieur.',
    'cta.subtitle': 'Contactez-nous pour un audit gratuit de votre infrastructure.',
    'cta.button': 'Demander un audit',
    
    // Footer
    'footer.tagline': 'L\'IT managée. Moderne. Efficace.',
    'footer.rights': 'Tous droits réservés.',
    'footer.company': 'Entreprise',
    'footer.legal': 'Mentions légales',
    'footer.privacy': 'Confidentialité',
    
    // About
    'about.title': 'À propos de Tekio',
    'about.mission.title': 'Notre mission',
    'about.mission.desc': 'Simplifier l\'IT des PME pour qu\'elles se concentrent sur leur cœur de métier.',
    'about.vision.title': 'Notre vision',
    'about.vision.desc': 'Devenir le MSP de référence pour les micro-PME grâce à l\'automatisation et l\'IA.',
    'about.founder.title': 'Fondateur',
    'about.founder.name': 'Jawade El Hadouchi',
    'about.founder.desc': 'Plus de 15 ans d\'expérience en IT et infrastructure.',
    'about.values.title': 'Nos valeurs',
    'about.values.simple': 'Simple',
    'about.values.clear': 'Clair',
    'about.values.efficient': 'Efficace',
    
    // Contact
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Une question ? Un projet ? Parlons-en.',
    'contact.name': 'Nom',
    'contact.email': 'Email',
    'contact.company': 'Entreprise',
    'contact.message': 'Message',
    'contact.send': 'Envoyer',
    'contact.info.title': 'Coordonnées',
    'contact.info.address': 'Bruxelles, Belgique',
    
    // Audit
    'audit.title': 'Audit IT gratuit',
    'audit.subtitle': 'Découvrez les points d\'amélioration de votre infrastructure.',
    'audit.benefit1': 'Analyse complète de votre parc',
    'audit.benefit2': 'Identification des risques',
    'audit.benefit3': 'Recommandations personnalisées',
    'audit.benefit4': 'Rapport détaillé offert',
    'audit.cta': 'Demander mon audit',
    
    // Method
    'method.title': 'Notre méthode',
    'method.subtitle': 'Une approche structurée et innovante.',
    'method.itil.title': 'ITIL',
    'method.itil.desc': 'Processus basés sur les meilleures pratiques ITIL.',
    'method.itil.details': 'Gestion des incidents, des changements et des problèmes selon les standards internationaux.',
    'method.automation.title': 'Automatisation',
    'method.automation.desc': 'Tâches répétitives automatisées pour plus d\'efficacité.',
    'method.automation.details': 'Scripts automatisés, déploiements sans intervention, maintenance préventive.',
    'method.ai.title': 'Intelligence artificielle',
    'method.ai.desc': 'IA pour la détection et résolution proactive des incidents.',
    'method.ai.details': 'Analyse prédictive, résolution automatique des incidents récurrents, chatbot intelligent.',
    'method.ai.badge': 'Intelligence Artificielle',
    'method.ai.hero.title': 'L\'IA au service de votre productivité',
    'method.ai.hero.desc': 'Notre plateforme intègre des capacités d\'intelligence artificielle pour anticiper les problèmes, automatiser les tâches répétitives et vous offrir un support toujours plus rapide et pertinent.',
    'method.ai.hero.cta': 'Découvrir nos capacités IA',
    'method.reporting.title': 'Reporting',
    'method.reporting.desc': 'Visibilité totale avec des rapports mensuels clairs.',
    'method.reporting.details': 'Dashboards en temps réel, rapports mensuels détaillés, KPIs personnalisés.',
    
    // Services Details
    'services.detail.support.1': 'Réponse en moins de 15 minutes',
    'services.detail.support.2': 'Support multicanal (téléphone, email, chat)',
    'services.detail.support.3': 'Base de connaissances accessible 24/7',
    'services.detail.support.4': 'Suivi des tickets en temps réel',
    'services.detail.cloud.1': 'Migration Office 365 complète',
    'services.detail.cloud.2': 'Configuration et optimisation',
    'services.detail.cloud.3': 'Formation des utilisateurs',
    'services.detail.cloud.4': 'Gestion des licences',
    'services.detail.security.1': 'Antivirus et anti-malware managé',
    'services.detail.security.2': 'Backup automatisé cloud',
    'services.detail.security.3': 'Test de récupération mensuel',
    'services.detail.security.4': 'Monitoring des menaces 24/7',
    'services.detail.telecom.1': 'Téléphonie VoIP professionnelle',
    'services.detail.telecom.2': 'Intégration Teams / Microsoft',
    'services.detail.telecom.3': 'Numéros locaux et internationaux',
    'services.detail.telecom.4': 'Portabilité garantie',
    'services.detail.projects.1': 'Migration infrastructure complète',
    'services.detail.projects.2': 'Déploiement de nouveaux sites',
    'services.detail.projects.3': 'Audit et conseil technique',
    'services.detail.projects.4': 'Gestion de projet dédiée',
    'services.cta.discover': 'Découvrez tous nos services',
    'services.cta.learn': 'En savoir plus',
    
    // Audit Page
    'audit.free': '100% Gratuit',
    'audit.includes.title': 'Ce que comprend notre audit',
    'audit.process.title': 'Comment ça marche ?',
    'audit.process.step1': 'Remplissez le formulaire',
    'audit.process.step2': 'Nous planifions un appel de 30 min',
    'audit.process.step3': 'Recevez votre rapport personnalisé',
    'audit.form.title': 'Demander mon audit gratuit',
    'audit.form.firstName': 'Prénom',
    'audit.form.lastName': 'Nom',
    'audit.form.email': 'Email professionnel',
    'audit.form.company': 'Entreprise',
    'audit.form.phone': 'Téléphone',
    'audit.form.employees': 'Nombre d\'employés',
    'audit.form.needs': 'Vos besoins principaux',
    'audit.form.placeholder.firstName': 'Jean',
    'audit.form.placeholder.lastName': 'Dupont',
    'audit.form.placeholder.email': 'jean@entreprise.be',
    'audit.form.placeholder.company': 'Nom de votre entreprise',
    'audit.form.placeholder.phone': '+32 XXX XX XX XX',
    'audit.form.placeholder.needs': 'Décrivez brièvement votre situation IT actuelle...',
    'audit.form.select.placeholder': 'Sélectionnez',
    'audit.form.submit.sending': 'Envoi en cours...',
    'audit.form.privacy': 'En soumettant ce formulaire, vous acceptez d\'être contacté par Tekio.',
    'audit.toast.success.title': 'Demande envoyée !',
    'audit.toast.success.desc': 'Nous vous contacterons sous 24h pour planifier votre audit.',
    
    // Pricing Page
    'pricing.plan.bronze.desc': 'Pour les petites équipes qui démarrent',
    'pricing.plan.silver.desc': 'L\'équilibre parfait pour les PME',
    'pricing.plan.gold.desc': 'Service premium tout inclus',
    'pricing.questions.title': 'Des questions sur nos offres ?',
    'pricing.questions.desc': 'Chaque entreprise est unique. Contactez-nous pour une offre personnalisée adaptée à vos besoins.',
    'pricing.dialog.title': 'Demander un devis',
    'pricing.dialog.desc': 'Remplissez ce formulaire et nous vous contacterons avec une offre personnalisée.',
    'pricing.dialog.name': 'Nom',
    'pricing.dialog.email': 'Email',
    'pricing.dialog.company': 'Entreprise',
    'pricing.dialog.employees': 'Nombre d\'utilisateurs',
    'pricing.dialog.message': 'Message (optionnel)',
    'pricing.dialog.placeholder.name': 'Votre nom',
    'pricing.dialog.placeholder.email': 'vous@entreprise.be',
    'pricing.dialog.placeholder.company': 'Nom de votre entreprise',
    'pricing.dialog.placeholder.message': 'Des besoins spécifiques ?',
    'pricing.dialog.submit': 'Envoyer ma demande',
    'pricing.dialog.submit.sending': 'Envoi...',
    'pricing.toast.success.title': 'Demande envoyée !',
    'pricing.toast.success.desc': 'Nous vous contacterons rapidement avec une offre personnalisée.',
    'pricing.interest.prefix': 'Plan intéressé:',
    
    // About Page
    'about.hero.tagline': 'Un MSP moderne basé à Bruxelles, dédié aux micro-PME.',
    'about.founder.quote': 'Mon objectif est simple : offrir aux PME les mêmes outils et le même niveau de service que les grandes entreprises, mais à un prix accessible et avec une approche humaine.',
    'about.cta.ready': 'Prêt à simplifier votre IT ?',
    'about.cta.discuss': 'Parlons de votre projet',
    
    // Contact Page
    'contact.form.placeholder.name': 'John Doe',
    'contact.form.placeholder.email': 'john@company.be',
    'contact.form.placeholder.company': 'Votre entreprise',
    'contact.form.placeholder.message': 'Comment pouvons-nous vous aider ?',
    'contact.form.submit.sending': 'Envoi en cours...',
    'contact.info.address.label': 'Adresse',
    'contact.info.email.label': 'Email',
    'contact.info.phone.label': 'WhatsApp Business',
      'contact.toast.success.title': 'Message envoyé !',
      'contact.toast.success.desc': 'Nous vous répondrons dans les plus brefs délais.',

      // Admin - Leads List
      'admin.leads.title': 'Gestion des Leads',
      'admin.leads.subtitle': 'Tekio Admin',
      'admin.leads.back': 'Retour au site',
      'admin.leads.filter': 'Filtrer par statut',
      'admin.leads.reset': 'Réinitialiser',
      'admin.leads.loading': 'Chargement...',
      'admin.leads.error': 'Erreur lors du chargement des leads',
      'admin.leads.empty': 'Aucun lead trouvé',
      'admin.leads.all': 'Tous les leads',
      'admin.leads.table.date': 'Date',
      'admin.leads.table.company': 'Entreprise',
      'admin.leads.table.contact': 'Contact',
      'admin.leads.table.email': 'Email',
      'admin.leads.table.users': 'Utilisateurs',
      'admin.leads.table.source': 'Source',
      'admin.leads.table.status': 'Statut',
      'admin.leads.table.actions': 'Actions',

      // Admin - Lead Detail
      'admin.lead.back': 'Retour',
      'admin.lead.id': 'Lead #',
      'admin.lead.info': 'Informations du lead',
      'admin.lead.company': 'Entreprise',
      'admin.lead.contact': 'Contact',
      'admin.lead.email': 'Email',
      'admin.lead.phone': 'Téléphone',
      'admin.lead.language': 'Langue',
      'admin.lead.users': 'Nb utilisateurs',
      'admin.lead.created': 'Date de création',
      'admin.lead.source': 'Source',
      'admin.lead.message': 'Message',
      'admin.lead.ai.title': 'Réponse IA suggérée',
      'admin.lead.ai.generate': 'Générer une réponse',
      'admin.lead.ai.generating': 'Génération...',
      'admin.lead.ai.copy': 'Copier la réponse',
      'admin.lead.ai.copied': 'Copié !',
      'admin.lead.ai.empty': 'Cliquez sur "Générer une réponse" pour obtenir une suggestion d\'email personnalisée.',
      'admin.lead.status.title': 'Statut',
      'admin.lead.status.new': 'Nouveau',
      'admin.lead.status.contacted': 'Contacté',
      'admin.lead.status.proposal': 'Proposition',
      'admin.lead.status.won': 'Gagné',
      'admin.lead.status.lost': 'Perdu',
      'admin.lead.notes.title': 'Notes internes',
      'admin.lead.notes.placeholder': 'Ajoutez vos notes ici...',
      'admin.lead.notes.save': 'Sauvegarder',
      'admin.lead.notes.saving': 'Sauvegarde...',
      'admin.lead.actions.title': 'Actions rapides',
      'admin.lead.actions.email': 'Envoyer un email',
      'admin.lead.actions.call': 'Appeler',
      'admin.lead.loading': 'Chargement...',
      'admin.lead.notfound': 'Lead non trouvé',
      'admin.lead.notfound.back': 'Retour à la liste',
      'admin.lead.toast.copied.title': 'Copié !',
      'admin.lead.toast.copied.desc': 'La réponse a été copiée dans le presse-papier.',
      
      // Admin - Sources
      'admin.source.home': 'Accueil',
      'admin.source.audit_page': 'Page Audit',
      'admin.source.contact_page': 'Page Contact',
      'admin.source.pricing_page': 'Page Tarifs',

      // Legal Page
      'legal.title': 'Mentions légales',
      'legal.editor.title': '1. Éditeur du site',
      'legal.editor.intro': 'Le site https://www.tekio.be (ci-après « le Site ») est édité par :',
      'legal.editor.address': 'Siège social',
      'legal.editor.bce': 'Numéro d\'entreprise (BCE)',
      'legal.editor.vat': 'Numéro de TVA',
      'legal.editor.email': 'E-mail de contact',
      'legal.publisher.title': '2. Responsable de la publication',
      'legal.publisher.intro': 'Le responsable de la publication est :',
      'legal.publisher.role': 'en qualité de gérant de HDC-AZG SRL',
      'legal.host.title': '3. Hébergeur',
      'legal.host.intro': 'Le Site est hébergé par :',
      'legal.purpose.title': '4. Objet du site',
      'legal.purpose.intro': 'Le Site a pour objet de présenter les services de Tekio, marque exploitée par HDC-AZG SRL, notamment des services de :',
      'legal.purpose.service1': 'Managed Services Provider (MSP) et infogérance IT',
      'legal.purpose.service2': 'Gestion d\'infrastructures, support et monitoring',
      'legal.purpose.service3': 'Automatisation, cybersécurité et digitalisation pour entreprises',
      'legal.purpose.disclaimer': 'Les informations diffusées sur le Site le sont à titre indicatif et peuvent être modifiées à tout moment.',
      'legal.ip.title': '5. Propriété intellectuelle',
      'legal.ip.content1': 'L\'ensemble du contenu du Site (textes, images, logos, éléments graphiques, vidéos, icônes, structure, code) est la propriété exclusive de HDC-AZG SRL ou utilisé avec l\'autorisation de tiers.',
      'legal.ip.content2': 'Toute reproduction, représentation, adaptation ou diffusion, totale ou partielle, par quelque procédé que ce soit, sans autorisation écrite préalable, est interdite et peut constituer une contrefaçon.',
      'legal.links.title': '6. Liens hypertextes',
      'legal.links.content1': 'Le Site peut contenir des liens vers d\'autres sites internet. HDC-AZG SRL n\'exerce aucun contrôle sur ces sites et ne peut être tenue responsable de leur contenu, de leur fonctionnement ou de leur légalité.',
      'legal.links.content2': 'La création de liens vers le Site est autorisée sous réserve :',
      'legal.links.condition1': 'de ne pas porter atteinte à l\'image ou à la réputation de Tekio ou HDC-AZG SRL',
      'legal.links.condition2': 'de ne pas suggérer faussement un partenariat ou un parrainage',
      'legal.links.content3': 'HDC-AZG SRL se réserve le droit de demander la suppression de tout lien qu\'elle jugerait inapproprié.',
      'legal.liability.title': '7. Responsabilité',
      'legal.liability.content1': 'HDC-AZG SRL met en œuvre des moyens raisonnables pour assurer l\'exactitude et la mise à jour des informations du Site. Toutefois :',
      'legal.liability.point1': 'aucune garantie n\'est donnée quant à l\'exhaustivité ou l\'actualité des informations',
      'legal.liability.point2': 'l\'éditeur ne peut être tenu responsable de dommages directs ou indirects résultant de l\'utilisation du Site ou de l\'impossibilité d\'y accéder',
      'legal.liability.point3': 'l\'utilisateur reste responsable de la protection de ses équipements et de ses données',
      'legal.liability.content2': 'Cette limitation de responsabilité ne s\'applique pas en cas de faute lourde, de fraude ou de dispositions légales impératives contraires.',
      'legal.jurisdiction.title': '8. Droit applicable et juridiction compétente',
      'legal.jurisdiction.content1': 'Les présentes Mentions légales sont régies par le droit belge.',
      'legal.jurisdiction.content2': 'À défaut de résolution amiable, tout litige relatif à l\'utilisation du Site sera soumis aux tribunaux compétents de l\'arrondissement judiciaire de Bruxelles, sans préjudice des règles impératives de compétence.',

      // Privacy Page
      'privacy.title': 'Politique de confidentialité & Cookies',
      'privacy.controller.title': '1. Responsable du traitement',
      'privacy.controller.intro': 'Le responsable du traitement des données à caractère personnel est :',
      'privacy.controller.email': 'E-mail de contact pour la protection des données',
      'privacy.controller.dpo': 'Aucun délégué à la protection des données (DPO) n\'est formellement désigné. Toute question relative à la vie privée peut être adressée à cette adresse.',
      'privacy.data.title': '2. Données collectées',
      'privacy.data.user.title': '2.1. Données fournies par l\'utilisateur',
      'privacy.data.user.intro': 'Via le formulaire de contact ou les échanges avec Tekio, les données suivantes peuvent être collectées :',
      'privacy.data.user.item1': 'Nom et prénom',
      'privacy.data.user.item2': 'Adresse e-mail',
      'privacy.data.user.item3': 'Numéro de téléphone',
      'privacy.data.user.item4': 'Nom de l\'entreprise et fonction',
      'privacy.data.user.item5': 'Contenu du message ou de la demande',
      'privacy.data.user.item6': 'Informations nécessaires à l\'établissement d\'un devis ou d\'un contrat',
      'privacy.data.auto.title': '2.2. Données collectées automatiquement',
      'privacy.data.auto.intro': 'Lors de la navigation sur le Site, certaines données techniques sont collectées automatiquement :',
      'privacy.data.auto.item1': 'Adresse IP',
      'privacy.data.auto.item2': 'Type de navigateur et système d\'exploitation',
      'privacy.data.auto.item3': 'Pages consultées, durée de visite',
      'privacy.data.auto.item4': 'Données de logs techniques',
      'privacy.data.auto.item5': 'Cookies et traceurs (voir section 7)',
      'privacy.data.msp.title': '2.3. Données dans le cadre des services MSP',
      'privacy.data.msp.intro': 'Dans le cadre de la fourniture de services IT / MSP, Tekio peut être amenée à traiter, pour le compte de ses clients :',
      'privacy.data.msp.item1': 'Informations de configuration technique',
      'privacy.data.msp.item2': 'Logs de systèmes et journaux d\'événements',
      'privacy.data.msp.item3': 'Données relatives au support et aux incidents',
      'privacy.data.msp.item4': 'Données de facturation et d\'identification de contacts techniques',
      'privacy.data.msp.disclaimer': 'Ces données sont traitées conformément aux contrats conclus avec chaque client et aux instructions écrites du client lorsque Tekio agit en tant que sous-traitant.',
      'privacy.purposes.title': '3. Finalités et bases légales',
      'privacy.purposes.intro': 'Les données sont traitées pour les finalités suivantes :',
      'privacy.purposes.purpose1.title': 'Gestion des demandes de contact et de devis',
      'privacy.purposes.purpose1.desc': 'Réception et réponse aux messages envoyés via le Site ou par e-mail',
      'privacy.purposes.purpose1.basis': 'Base légale : mesures précontractuelles et intérêt légitime',
      'privacy.purposes.purpose2.title': 'Gestion de la relation client et exécution des services MSP',
      'privacy.purposes.purpose2.desc': 'Mise en place, fourniture et suivi des services. Facturation, support, maintenance.',
      'privacy.purposes.purpose2.basis': 'Base légale : exécution du contrat',
      'privacy.purposes.purpose3.title': 'Prospection et communication B2B raisonnable',
      'privacy.purposes.purpose3.desc': 'Envoi d\'informations en lien avec les services Tekio à des contacts professionnels',
      'privacy.purposes.purpose3.basis': 'Base légale : intérêt légitime, dans le respect du cadre applicable en matière de prospection B2B',
      'privacy.purposes.purpose4.title': 'Amélioration du Site et statistiques d\'audience',
      'privacy.purposes.purpose4.desc': 'Analyse de la fréquentation via Google Analytics (après consentement)',
      'privacy.purposes.purpose4.basis': 'Base légale : consentement pour les cookies d\'analytics',
      'privacy.purposes.purpose5.title': 'Respect des obligations légales',
      'privacy.purposes.purpose5.desc': 'Conservation des documents comptables, obligations fiscales et légales',
      'privacy.purposes.purpose5.basis': 'Base légale : obligations légales applicables',
      'privacy.recipients.title': '4. Destinataires des données',
      'privacy.recipients.intro': 'Les données peuvent être accessibles :',
      'privacy.recipients.item1': 'Au personnel de HDC-AZG SRL habilité à les traiter',
      'privacy.recipients.item2': 'À des prestataires techniques agissant en qualité de sous-traitants (Hébergeur : OVH, Outil d\'analytics : Google Analytics, CRM : HubSpot)',
      'privacy.recipients.disclaimer': 'Ces sous-traitants sont contractuellement tenus de respecter la confidentialité et de mettre en œuvre des mesures de sécurité appropriées. Les données ne sont pas revendues à des tiers.',
      'privacy.transfers.title': '5. Transferts de données hors de l\'UE',
      'privacy.transfers.intro': 'Certains prestataires (ex. Google, HubSpot) peuvent être situés en dehors de l\'Espace économique européen (EEE). Dans ce cas, Tekio veille à ce que des garanties appropriées soient mises en place, telles que :',
      'privacy.transfers.item1': 'des clauses contractuelles types adoptées par la Commission européenne',
      'privacy.transfers.item2': 'des mesures complémentaires de sécurité et de confidentialité',
      'privacy.transfers.item3': 'ou l\'utilisation de prestataires bénéficiant d\'un niveau de protection adéquat reconnu',
      'privacy.retention.title': '6. Durée de conservation',
      'privacy.retention.intro': 'Les données sont conservées pendant des durées limitées :',
      'privacy.retention.item1': 'Données de contact (prospects) : jusqu\'à 3 ans après le dernier contact significatif, sauf opposition',
      'privacy.retention.item2': 'Données clients et documents contractuels : pendant la durée du contrat, puis selon les obligations légales (notamment comptables)',
      'privacy.retention.item3': 'Logs techniques et données de sécurité : en général entre 6 mois et 1 an, sauf nécessité particulière',
      'privacy.retention.item4': 'Cookies : durée variable selon leur nature (voir section 7)',
      'privacy.retention.disclaimer': 'À l\'issue de ces durées, les données sont supprimées, anonymisées ou archivées lorsque la loi l\'exige.',
      'privacy.cookies.title': '7. Cookies',
      'privacy.cookies.intro': 'Le Site utilise des cookies et technologies similaires :',
      'privacy.cookies.essential.title': '7.1. Cookies strictement nécessaires',
      'privacy.cookies.essential.desc': 'Ces cookies sont indispensables au fonctionnement du Site (sécurité, affichage, langue, etc.). Ils ne peuvent pas être désactivés via le bandeau de consentement.',
      'privacy.cookies.analytics.title': '7.2. Cookies de mesure d\'audience (Google Analytics)',
      'privacy.cookies.analytics.desc': 'Sous réserve de votre consentement, des cookies de mesure d\'audience peuvent être déposés afin d\'analyser la fréquentation du Site et améliorer le contenu et l\'ergonomie. Ces cookies ne sont activés qu\'après acceptation via le bandeau de cookies.',
      'privacy.cookies.consent.title': '7.3. Gestion du consentement',
      'privacy.cookies.consent.desc': 'Lors de votre première visite, un bandeau vous permet d\'accepter ou refuser les cookies non essentiels, et de modifier vos préférences ultérieurement. Vous pouvez également configurer votre navigateur pour bloquer certains cookies, mais cela peut affecter certaines fonctionnalités.',
      'privacy.confidentiality.title': '8. Confidentialité dans le cadre des services MSP',
      'privacy.confidentiality.content1': 'Tekio s\'engage à traiter comme strictement confidentielles toutes les informations, données et configurations auxquelles elle accède dans le cadre de ses prestations : infrastructures, systèmes et environnements techniques, données de logs, sauvegardes, configurations, informations commerciales ou stratégiques des clients.',
      'privacy.confidentiality.content2': 'Sauf accord écrit du client ou obligation légale, ces informations ne sont ni divulguées ni utilisées à d\'autres fins que l\'exécution des services convenus. Tekio veille également à ce que ses sous-traitants et partenaires soient soumis à des obligations de confidentialité équivalentes.',
      'privacy.rights.title': '9. Vos droits',
      'privacy.rights.intro': 'Conformément au Règlement (UE) 2016/679 (RGPD), vous disposez des droits suivants :',
      'privacy.rights.item1': 'Droit d\'accès à vos données',
      'privacy.rights.item2': 'Droit de rectification',
      'privacy.rights.item3': 'Droit à l\'effacement (dans les limites légales)',
      'privacy.rights.item4': 'Droit à la limitation du traitement',
      'privacy.rights.item5': 'Droit d\'opposition, notamment en cas de prospection',
      'privacy.rights.item6': 'Droit à la portabilité des données (dans certains cas)',
      'privacy.rights.contact': 'Données personnelles',
      'privacy.rights.identity': 'Une preuve d\'identité peut être demandée en cas de doute raisonnable.',
      'privacy.complaint.title': '10. Réclamation auprès de l\'autorité de contrôle',
      'privacy.complaint.intro': 'Si vous estimez que vos droits ne sont pas respectés, vous pouvez introduire une réclamation auprès de :',
      'privacy.updates.title': '11. Mise à jour de la politique',
      'privacy.updates.content': 'La présente Politique de confidentialité peut être mise à jour pour tenir compte de l\'évolution des services, de la législation ou de la technologie. La version en vigueur est celle publiée sur le Site à la date de consultation.',
      
      // Admin - Languages
      'admin.lang.FR': 'Français',
      'admin.lang.NL': 'Nederlands',
      'admin.lang.EN': 'English',
  },
  nl: {
    // Navigation
    'nav.home': 'Home',
    'nav.services': 'Diensten',
    'nav.pricing': 'Prijzen',
    'nav.method': 'Methode & AI',
    'nav.about': 'Over ons',
    'nav.contact': 'Contact',
    'nav.audit': 'Gratis audit',
    
    // Hero
    'hero.title': 'Managed IT.',
    'hero.title2': 'Modern. Efficiënt.',
    'hero.subtitle': 'Tekio vereenvoudigt en centraliseert uw IT. Eenvoudig, duidelijk, zonder gedoe.',
    'hero.cta1': 'Gratis audit',
    'hero.cta2': 'Met een expert spreken',
    
    // Why Tekio
    'why.title': 'Waarom Tekio?',
    'why.subtitle': 'Een moderne aanpak van IT-beheer voor KMO\'s.',
    'why.support.title': 'Snelle support',
    'why.support.desc': 'Reactie binnen 15 minuten. Uw team blijft nooit vastzitten.',
    'why.security.title': 'Beveiliging 24/7',
    'why.security.desc': 'Continue monitoring en proactieve bescherming van uw infrastructuur.',
    'why.automation.title': 'Automatisering & AI',
    'why.automation.desc': 'Kunstmatige intelligentie ten dienste van uw productiviteit.',
    
    // Services
    'services.title': 'Onze diensten',
    'services.subtitle': 'Alles wat uw bedrijf nodig heeft, gecentraliseerd.',
    'services.support.title': 'Support & Helpdesk',
    'services.support.desc': 'Reactieve technische ondersteuning voor uw teams.',
    'services.cloud.title': 'Microsoft 365 & Cloud',
    'services.cloud.desc': 'Migratie, configuratie en beheer van uw cloud-tools.',
    'services.security.title': 'Beveiliging & Backup',
    'services.security.desc': 'Geavanceerde bescherming en back-up van uw gegevens.',
    'services.telecom.title': 'Telecom & VoIP',
    'services.telecom.desc': 'Moderne en flexibele communicatieoplossingen.',
    'services.projects.title': 'Projecten & Migraties',
    'services.projects.desc': 'Begeleiding bij uw transformatieprojecten.',
    
    // Technology
    'tech.title': 'Onze technologie',
    'tech.subtitle': 'Moderne tools voor performante IT.',
    'tech.ai.title': 'Geïntegreerde AI',
    'tech.ai.desc': 'Intelligente incidentoplossing.',
    'tech.automation.title': 'Automatiseringen',
    'tech.automation.desc': 'Geoptimaliseerde processen en geautomatiseerde taken.',
    'tech.dashboard.title': 'Dashboards',
    'tech.dashboard.desc': 'Volledige zichtbaarheid op uw infrastructuur.',
    'tech.reporting.title': 'Duidelijke rapportage',
    'tech.reporting.desc': 'Gedetailleerde en begrijpelijke maandelijkse rapporten.',
    
    // Pricing
    'pricing.title': 'Onze MSP-aanbiedingen',
    'pricing.subtitle': 'Formules aangepast aan uw behoeften.',
    'pricing.setup': 'Setup gratis bij 12-maanden contract',
    'pricing.per.user': '/gebruiker/maand',
    'pricing.cta': 'Starten',
    'pricing.popular': 'Populair',
    'pricing.bronze.name': 'Bronze',
    'pricing.silver.name': 'Silver',
    'pricing.gold.name': 'Gold',
    'pricing.bronze.price': '29€',
    'pricing.silver.price': '49€',
    'pricing.gold.price': '79€',
    'pricing.feature.support': 'Helpdesk support',
    'pricing.feature.monitoring': 'Monitoring',
    'pricing.feature.backup': 'Cloud backup',
    'pricing.feature.security': 'Geavanceerde beveiliging',
    'pricing.feature.m365': 'Microsoft 365 beheer',
    'pricing.feature.voip': 'VoIP inbegrepen',
    'pricing.feature.ai': 'AI & automatisering',
    'pricing.feature.dedicated': 'Toegewijde engineer',
    
    // CTA Final
    'cta.title': 'Breng uw IT naar het volgende niveau.',
    'cta.subtitle': 'Neem contact met ons op voor een gratis audit van uw infrastructuur.',
    'cta.button': 'Audit aanvragen',
    
    // Footer
    'footer.tagline': 'Managed IT. Modern. Efficiënt.',
    'footer.rights': 'Alle rechten voorbehouden.',
    'footer.company': 'Bedrijf',
    'footer.legal': 'Juridische informatie',
    'footer.privacy': 'Privacy',
    
    // About
    'about.title': 'Over Tekio',
    'about.mission.title': 'Onze missie',
    'about.mission.desc': 'De IT van KMO\'s vereenvoudigen zodat zij zich kunnen concentreren op hun kernactiviteit.',
    'about.vision.title': 'Onze visie',
    'about.vision.desc': 'De referentie MSP worden voor micro-KMO\'s dankzij automatisering en AI.',
    'about.founder.title': 'Oprichter',
    'about.founder.name': 'Jawade El Hadouchi',
    'about.founder.desc': 'Meer dan 15 jaar ervaring in IT en infrastructuur.',
    'about.values.title': 'Onze waarden',
    'about.values.simple': 'Eenvoudig',
    'about.values.clear': 'Duidelijk',
    'about.values.efficient': 'Efficiënt',
    
    // Contact
    'contact.title': 'Contacteer ons',
    'contact.subtitle': 'Een vraag? Een project? Laten we praten.',
    'contact.name': 'Naam',
    'contact.email': 'E-mail',
    'contact.company': 'Bedrijf',
    'contact.message': 'Bericht',
    'contact.send': 'Verzenden',
    'contact.info.title': 'Contactgegevens',
    'contact.info.address': 'Brussel, België',
    
    // Audit
    'audit.title': 'Gratis IT-audit',
    'audit.subtitle': 'Ontdek de verbeterpunten van uw infrastructuur.',
    'audit.benefit1': 'Volledige analyse van uw IT-park',
    'audit.benefit2': 'Identificatie van risico\'s',
    'audit.benefit3': 'Gepersonaliseerde aanbevelingen',
    'audit.benefit4': 'Gedetailleerd rapport gratis',
    'audit.cta': 'Mijn audit aanvragen',
    
    // Method
    'method.title': 'Onze methode',
    'method.subtitle': 'Een gestructureerde en innovatieve aanpak.',
    'method.itil.title': 'ITIL',
    'method.itil.desc': 'Processen gebaseerd op ITIL best practices.',
    'method.itil.details': 'Beheer van incidenten, wijzigingen en problemen volgens internationale normen.',
    'method.automation.title': 'Automatisering',
    'method.automation.desc': 'Geautomatiseerde repetitieve taken voor meer efficiëntie.',
    'method.automation.details': 'Geautomatiseerde scripts, implementaties zonder interventie, preventief onderhoud.',
    'method.ai.title': 'Kunstmatige intelligentie',
    'method.ai.desc': 'AI voor proactieve detectie en oplossing van incidenten.',
    'method.ai.details': 'Voorspellende analyse, automatische oplossing van terugkerende incidenten, intelligente chatbot.',
    'method.ai.badge': 'Kunstmatige Intelligentie',
    'method.ai.hero.title': 'AI ten dienste van uw productiviteit',
    'method.ai.hero.desc': 'Ons platform integreert kunstmatige intelligentie-mogelijkheden om problemen te anticiperen, repetitieve taken te automatiseren en u altijd snellere en relevantere ondersteuning te bieden.',
    'method.ai.hero.cta': 'Ontdek onze AI-mogelijkheden',
    'method.reporting.title': 'Rapportage',
    'method.reporting.desc': 'Totale zichtbaarheid met duidelijke maandelijkse rapporten.',
    'method.reporting.details': 'Real-time dashboards, gedetailleerde maandelijkse rapporten, gepersonaliseerde KPI\'s.',
    
    // Services Details
    'services.detail.support.1': 'Reactie binnen 15 minuten',
    'services.detail.support.2': 'Multi-channel support (telefoon, e-mail, chat)',
    'services.detail.support.3': 'Kennisbank 24/7 toegankelijk',
    'services.detail.support.4': 'Real-time ticketopvolging',
    'services.detail.cloud.1': 'Volledige Office 365-migratie',
    'services.detail.cloud.2': 'Configuratie en optimalisatie',
    'services.detail.cloud.3': 'Gebruikerstraining',
    'services.detail.cloud.4': 'Licentiebeheer',
    'services.detail.security.1': 'Beheerde antivirus en anti-malware',
    'services.detail.security.2': 'Geautomatiseerde cloud backup',
    'services.detail.security.3': 'Maandelijkse hersteltest',
    'services.detail.security.4': '24/7 dreigingsbewaking',
    'services.detail.telecom.1': 'Professionele VoIP-telefonie',
    'services.detail.telecom.2': 'Teams / Microsoft-integratie',
    'services.detail.telecom.3': 'Lokale en internationale nummers',
    'services.detail.telecom.4': 'Gegarandeerde portabiliteit',
    'services.detail.projects.1': 'Volledige infrastructuurmigratie',
    'services.detail.projects.2': 'Uitrol van nieuwe sites',
    'services.detail.projects.3': 'Audit en technisch advies',
    'services.detail.projects.4': 'Toegewijd projectbeheer',
    'services.cta.discover': 'Ontdek al onze diensten',
    'services.cta.learn': 'Meer weten',
    
    // Audit Page
    'audit.free': '100% Gratis',
    'audit.includes.title': 'Wat onze audit omvat',
    'audit.process.title': 'Hoe werkt het?',
    'audit.process.step1': 'Vul het formulier in',
    'audit.process.step2': 'We plannen een gesprek van 30 min',
    'audit.process.step3': 'Ontvang uw gepersonaliseerd rapport',
    'audit.form.title': 'Vraag mijn gratis audit aan',
    'audit.form.firstName': 'Voornaam',
    'audit.form.lastName': 'Achternaam',
    'audit.form.email': 'Professionele e-mail',
    'audit.form.company': 'Bedrijf',
    'audit.form.phone': 'Telefoon',
    'audit.form.employees': 'Aantal werknemers',
    'audit.form.needs': 'Uw belangrijkste behoeften',
    'audit.form.placeholder.firstName': 'Jan',
    'audit.form.placeholder.lastName': 'Janssen',
    'audit.form.placeholder.email': 'jan@bedrijf.be',
    'audit.form.placeholder.company': 'Naam van uw bedrijf',
    'audit.form.placeholder.phone': '+32 XXX XX XX XX',
    'audit.form.placeholder.needs': 'Beschrijf kort uw huidige IT-situatie...',
    'audit.form.select.placeholder': 'Selecteer',
    'audit.form.submit.sending': 'Verzenden...',
    'audit.form.privacy': 'Door dit formulier in te dienen, gaat u ermee akkoord te worden gecontacteerd door Tekio.',
    'audit.toast.success.title': 'Aanvraag verzonden!',
    'audit.toast.success.desc': 'We nemen binnen 24 uur contact met u op om uw audit te plannen.',
    
    // Pricing Page
    'pricing.plan.bronze.desc': 'Voor kleine teams die starten',
    'pricing.plan.silver.desc': 'De perfecte balans voor KMO\'s',
    'pricing.plan.gold.desc': 'Premium all-inclusive service',
    'pricing.questions.title': 'Vragen over onze aanbiedingen?',
    'pricing.questions.desc': 'Elk bedrijf is uniek. Neem contact met ons op voor een gepersonaliseerd aanbod aangepast aan uw behoeften.',
    'pricing.dialog.title': 'Een offerte aanvragen',
    'pricing.dialog.desc': 'Vul dit formulier in en we nemen contact met u op met een gepersonaliseerd aanbod.',
    'pricing.dialog.name': 'Naam',
    'pricing.dialog.email': 'E-mail',
    'pricing.dialog.company': 'Bedrijf',
    'pricing.dialog.employees': 'Aantal gebruikers',
    'pricing.dialog.message': 'Bericht (optioneel)',
    'pricing.dialog.placeholder.name': 'Uw naam',
    'pricing.dialog.placeholder.email': 'u@bedrijf.be',
    'pricing.dialog.placeholder.company': 'Naam van uw bedrijf',
    'pricing.dialog.placeholder.message': 'Specifieke behoeften?',
    'pricing.dialog.submit': 'Mijn aanvraag verzenden',
    'pricing.dialog.submit.sending': 'Verzenden...',
    'pricing.toast.success.title': 'Aanvraag verzonden!',
    'pricing.toast.success.desc': 'We nemen snel contact met u op met een gepersonaliseerd aanbod.',
    'pricing.interest.prefix': 'Interessant plan:',
    
    // About Page
    'about.hero.tagline': 'Een moderne MSP gevestigd in Brussel, toegewijd aan micro-KMO\'s.',
    'about.founder.quote': 'Mijn doel is eenvoudig: KMO\'s dezelfde tools en hetzelfde serviceniveau bieden als grote bedrijven, maar tegen een betaalbare prijs en met een menselijke aanpak.',
    'about.cta.ready': 'Klaar om uw IT te vereenvoudigen?',
    'about.cta.discuss': 'Laten we over uw project praten',
    
    // Contact Page
    'contact.form.placeholder.name': 'John Doe',
    'contact.form.placeholder.email': 'john@bedrijf.be',
    'contact.form.placeholder.company': 'Uw bedrijf',
    'contact.form.placeholder.message': 'Hoe kunnen we u helpen?',
    'contact.form.submit.sending': 'Verzenden...',
    'contact.info.address.label': 'Adres',
    'contact.info.email.label': 'E-mail',
    'contact.info.phone.label': 'WhatsApp Business',
      'contact.toast.success.title': 'Bericht verzonden!',
      'contact.toast.success.desc': 'We nemen zo snel mogelijk contact met u op.',

      // Admin - Leads List
      'admin.leads.title': 'Leadbeheer',
      'admin.leads.subtitle': 'Tekio Admin',
      'admin.leads.back': 'Terug naar site',
      'admin.leads.filter': 'Filteren op status',
      'admin.leads.reset': 'Reset',
      'admin.leads.loading': 'Laden...',
      'admin.leads.error': 'Fout bij het laden van leads',
      'admin.leads.empty': 'Geen leads gevonden',
      'admin.leads.all': 'Alle leads',
      'admin.leads.table.date': 'Datum',
      'admin.leads.table.company': 'Bedrijf',
      'admin.leads.table.contact': 'Contact',
      'admin.leads.table.email': 'E-mail',
      'admin.leads.table.users': 'Gebruikers',
      'admin.leads.table.source': 'Bron',
      'admin.leads.table.status': 'Status',
      'admin.leads.table.actions': 'Acties',

      // Admin - Lead Detail
      'admin.lead.back': 'Terug',
      'admin.lead.id': 'Lead #',
      'admin.lead.info': 'Leadinformatie',
      'admin.lead.company': 'Bedrijf',
      'admin.lead.contact': 'Contact',
      'admin.lead.email': 'E-mail',
      'admin.lead.phone': 'Telefoon',
      'admin.lead.language': 'Taal',
      'admin.lead.users': 'Aantal gebruikers',
      'admin.lead.created': 'Aanmaakdatum',
      'admin.lead.source': 'Bron',
      'admin.lead.message': 'Bericht',
      'admin.lead.ai.title': 'AI-antwoordsuggestie',
      'admin.lead.ai.generate': 'Antwoord genereren',
      'admin.lead.ai.generating': 'Genereren...',
      'admin.lead.ai.copy': 'Antwoord kopiëren',
      'admin.lead.ai.copied': 'Gekopieerd!',
      'admin.lead.ai.empty': 'Klik op "Antwoord genereren" om een gepersonaliseerde e-mailsuggestie te krijgen.',
      'admin.lead.status.title': 'Status',
      'admin.lead.status.new': 'Nieuw',
      'admin.lead.status.contacted': 'Gecontacteerd',
      'admin.lead.status.proposal': 'Voorstel',
      'admin.lead.status.won': 'Gewonnen',
      'admin.lead.status.lost': 'Verloren',
      'admin.lead.notes.title': 'Interne notities',
      'admin.lead.notes.placeholder': 'Voeg hier uw notities toe...',
      'admin.lead.notes.save': 'Opslaan',
      'admin.lead.notes.saving': 'Opslaan...',
      'admin.lead.actions.title': 'Snelle acties',
      'admin.lead.actions.email': 'E-mail verzenden',
      'admin.lead.actions.call': 'Bellen',
      'admin.lead.loading': 'Laden...',
      'admin.lead.notfound': 'Lead niet gevonden',
      'admin.lead.notfound.back': 'Terug naar lijst',
      'admin.lead.toast.copied.title': 'Gekopieerd!',
      'admin.lead.toast.copied.desc': 'Het antwoord is naar het klembord gekopieerd.',
      
      // Admin - Sources
      'admin.source.home': 'Home',
      'admin.source.audit_page': 'Auditpagina',
      'admin.source.contact_page': 'Contactpagina',
      'admin.source.pricing_page': 'Prijzenpagina',
      
      // Admin - Languages
      'admin.lang.FR': 'Frans',
      'admin.lang.NL': 'Nederlands',
      'admin.lang.EN': 'Engels',

      // Legal Page
      'legal.title': 'Juridische vermeldingen',
      'legal.editor.title': '1. Uitgever van de site',
      'legal.editor.intro': 'De website https://www.tekio.be (hierna "de Site") wordt uitgegeven door:',
      'legal.editor.address': 'Maatschappelijke zetel',
      'legal.editor.bce': 'Ondernemingsnummer (KBO)',
      'legal.editor.vat': 'BTW-nummer',
      'legal.editor.email': 'Contact e-mail',
      'legal.publisher.title': '2. Verantwoordelijke voor publicatie',
      'legal.publisher.intro': 'De verantwoordelijke voor de publicatie is:',
      'legal.publisher.role': 'in hoedanigheid van zaakvoerder van HDC-AZG SRL',
      'legal.host.title': '3. Hosting',
      'legal.host.intro': 'De Site wordt gehost door:',
      'legal.purpose.title': '4. Doel van de site',
      'legal.purpose.intro': 'De Site heeft als doel de diensten van Tekio voor te stellen, een merk uitgebaat door HDC-AZG SRL, met name diensten van:',
      'legal.purpose.service1': 'Managed Services Provider (MSP) en IT-beheer',
      'legal.purpose.service2': 'Infrastructuurbeheer, ondersteuning en monitoring',
      'legal.purpose.service3': 'Automatisering, cybersecurity en digitalisering voor bedrijven',
      'legal.purpose.disclaimer': 'De informatie op de Site wordt verstrekt ter indicatie en kan op elk moment worden gewijzigd.',
      'legal.ip.title': '5. Intellectueel eigendom',
      'legal.ip.content1': 'De volledige inhoud van de Site (teksten, afbeeldingen, logo\'s, grafische elementen, video\'s, iconen, structuur, code) is het exclusieve eigendom van HDC-AZG SRL of wordt gebruikt met toestemming van derden.',
      'legal.ip.content2': 'Elke reproductie, weergave, aanpassing of verspreiding, geheel of gedeeltelijk, door welk procédé dan ook, zonder voorafgaande schriftelijke toestemming, is verboden en kan een inbreuk vormen.',
      'legal.links.title': '6. Hyperlinks',
      'legal.links.content1': 'De Site kan links bevatten naar andere websites. HDC-AZG SRL heeft geen controle over deze sites en kan niet verantwoordelijk worden gehouden voor hun inhoud, werking of wettigheid.',
      'legal.links.content2': 'Het aanmaken van links naar de Site is toegestaan onder voorbehoud van:',
      'legal.links.condition1': 'het imago of de reputatie van Tekio of HDC-AZG SRL niet te schaden',
      'legal.links.condition2': 'geen vals partnerschap of sponsoring te suggereren',
      'legal.links.content3': 'HDC-AZG SRL behoudt zich het recht voor om de verwijdering te vragen van elke link die zij ongepast acht.',
      'legal.liability.title': '7. Aansprakelijkheid',
      'legal.liability.content1': 'HDC-AZG SRL zet redelijke middelen in om de juistheid en actualisering van de informatie op de Site te waarborgen. Echter:',
      'legal.liability.point1': 'er wordt geen garantie gegeven met betrekking tot de volledigheid of actualiteit van de informatie',
      'legal.liability.point2': 'de uitgever kan niet aansprakelijk worden gesteld voor directe of indirecte schade als gevolg van het gebruik van de Site of de onmogelijkheid om er toegang toe te krijgen',
      'legal.liability.point3': 'de gebruiker blijft verantwoordelijk voor de bescherming van zijn apparatuur en gegevens',
      'legal.liability.content2': 'Deze beperking van aansprakelijkheid geldt niet in geval van grove fout, fraude of dwingende wettelijke bepalingen die het tegendeel bepalen.',
      'legal.jurisdiction.title': '8. Toepasselijk recht en bevoegde rechtbank',
      'legal.jurisdiction.content1': 'Deze Juridische vermeldingen worden beheerst door het Belgisch recht.',
      'legal.jurisdiction.content2': 'Bij gebreke aan minnelijke schikking zal elk geschil met betrekking tot het gebruik van de Site worden voorgelegd aan de bevoegde rechtbanken van het gerechtelijk arrondissement Brussel, onverminderd de dwingende bevoegdheidsregels.',

      // Privacy Page
      'privacy.title': 'Privacybeleid & Cookies',
      'privacy.controller.title': '1. Verwerkingsverantwoordelijke',
      'privacy.controller.intro': 'De verwerkingsverantwoordelijke voor persoonsgegevens is:',
      'privacy.controller.email': 'Contact e-mail voor gegevensbescherming',
      'privacy.controller.dpo': 'Er is geen Data Protection Officer (DPO) formeel aangesteld. Elke vraag met betrekking tot privacy kan aan dit adres worden gericht.',
      'privacy.data.title': '2. Verzamelde gegevens',
      'privacy.data.user.title': '2.1. Door de gebruiker verstrekte gegevens',
      'privacy.data.user.intro': 'Via het contactformulier of uitwisselingen met Tekio kunnen de volgende gegevens worden verzameld:',
      'privacy.data.user.item1': 'Naam en voornaam',
      'privacy.data.user.item2': 'E-mailadres',
      'privacy.data.user.item3': 'Telefoonnummer',
      'privacy.data.user.item4': 'Bedrijfsnaam en functie',
      'privacy.data.user.item5': 'Inhoud van het bericht of de aanvraag',
      'privacy.data.user.item6': 'Informatie nodig voor het opstellen van een offerte of contract',
      'privacy.data.auto.title': '2.2. Automatisch verzamelde gegevens',
      'privacy.data.auto.intro': 'Tijdens het browsen op de Site worden bepaalde technische gegevens automatisch verzameld:',
      'privacy.data.auto.item1': 'IP-adres',
      'privacy.data.auto.item2': 'Type browser en besturingssysteem',
      'privacy.data.auto.item3': 'Bezochte pagina\'s, bezoekduur',
      'privacy.data.auto.item4': 'Technische loggegevens',
      'privacy.data.auto.item5': 'Cookies en trackers (zie sectie 7)',
      'privacy.data.msp.title': '2.3. Gegevens in het kader van MSP-diensten',
      'privacy.data.msp.intro': 'In het kader van IT/MSP-diensten kan Tekio namens haar klanten de volgende gegevens verwerken:',
      'privacy.data.msp.item1': 'Technische configuratie-informatie',
      'privacy.data.msp.item2': 'Systeemlogs en gebeurtenisjournalen',
      'privacy.data.msp.item3': 'Gegevens met betrekking tot support en incidenten',
      'privacy.data.msp.item4': 'Facturatie- en identificatiegegevens van technische contactpersonen',
      'privacy.data.msp.disclaimer': 'Deze gegevens worden verwerkt in overeenstemming met de contracten gesloten met elke klant en de schriftelijke instructies van de klant wanneer Tekio optreedt als verwerker.',
      'privacy.purposes.title': '3. Doeleinden en rechtsgronden',
      'privacy.purposes.intro': 'De gegevens worden verwerkt voor de volgende doeleinden:',
      'privacy.purposes.purpose1.title': 'Beheer van contact- en offerteaanvragen',
      'privacy.purposes.purpose1.desc': 'Ontvangst en beantwoording van berichten verzonden via de Site of per e-mail',
      'privacy.purposes.purpose1.basis': 'Rechtsgrond: precontractuele maatregelen en gerechtvaardigd belang',
      'privacy.purposes.purpose2.title': 'Beheer van klantrelaties en uitvoering van MSP-diensten',
      'privacy.purposes.purpose2.desc': 'Implementatie, levering en opvolging van diensten. Facturatie, support, onderhoud.',
      'privacy.purposes.purpose2.basis': 'Rechtsgrond: uitvoering van het contract',
      'privacy.purposes.purpose3.title': 'Redelijke B2B-prospectie en communicatie',
      'privacy.purposes.purpose3.desc': 'Verzending van informatie met betrekking tot Tekio-diensten aan professionele contacten',
      'privacy.purposes.purpose3.basis': 'Rechtsgrond: gerechtvaardigd belang, met respect voor het toepasselijke kader inzake B2B-prospectie',
      'privacy.purposes.purpose4.title': 'Verbetering van de Site en bezoekersstatistieken',
      'privacy.purposes.purpose4.desc': 'Analyse van het verkeer via Google Analytics (na toestemming)',
      'privacy.purposes.purpose4.basis': 'Rechtsgrond: toestemming voor analytics cookies',
      'privacy.purposes.purpose5.title': 'Naleving van wettelijke verplichtingen',
      'privacy.purposes.purpose5.desc': 'Bewaring van boekhoudkundige documenten, fiscale en wettelijke verplichtingen',
      'privacy.purposes.purpose5.basis': 'Rechtsgrond: toepasselijke wettelijke verplichtingen',
      'privacy.recipients.title': '4. Ontvangers van gegevens',
      'privacy.recipients.intro': 'De gegevens kunnen toegankelijk zijn voor:',
      'privacy.recipients.item1': 'Personeel van HDC-AZG SRL dat bevoegd is om ze te verwerken',
      'privacy.recipients.item2': 'Technische dienstverleners die optreden als verwerkers (Hosting: OVH, Analytics tool: Google Analytics, CRM: HubSpot)',
      'privacy.recipients.disclaimer': 'Deze verwerkers zijn contractueel verplicht de vertrouwelijkheid te respecteren en passende beveiligingsmaatregelen te implementeren. De gegevens worden niet doorverkocht aan derden.',
      'privacy.transfers.title': '5. Gegevensoverdrachten buiten de EU',
      'privacy.transfers.intro': 'Sommige dienstverleners (bv. Google, HubSpot) kunnen buiten de Europese Economische Ruimte (EER) gevestigd zijn. In dat geval zorgt Tekio ervoor dat passende waarborgen worden geïmplementeerd, zoals:',
      'privacy.transfers.item1': 'standaardcontractbepalingen aangenomen door de Europese Commissie',
      'privacy.transfers.item2': 'aanvullende beveiligings- en vertrouwelijkheidsmaatregelen',
      'privacy.transfers.item3': 'of het gebruik van dienstverleners die genieten van een erkend adequaat beschermingsniveau',
      'privacy.retention.title': '6. Bewaartermijn',
      'privacy.retention.intro': 'De gegevens worden gedurende beperkte periodes bewaard:',
      'privacy.retention.item1': 'Contactgegevens (prospects): tot 3 jaar na het laatste significante contact, tenzij bezwaar',
      'privacy.retention.item2': 'Klantgegevens en contractuele documenten: gedurende de looptijd van het contract, daarna volgens wettelijke verplichtingen (met name boekhoudkundige)',
      'privacy.retention.item3': 'Technische logs en beveiligingsgegevens: over het algemeen tussen 6 maanden en 1 jaar, tenzij bijzondere noodzaak',
      'privacy.retention.item4': 'Cookies: variabele duur afhankelijk van hun aard (zie sectie 7)',
      'privacy.retention.disclaimer': 'Na afloop van deze periodes worden de gegevens verwijderd, geanonimiseerd of gearchiveerd wanneer de wet dit vereist.',
      'privacy.cookies.title': '7. Cookies',
      'privacy.cookies.intro': 'De Site maakt gebruik van cookies en vergelijkbare technologieën:',
      'privacy.cookies.essential.title': '7.1. Strikt noodzakelijke cookies',
      'privacy.cookies.essential.desc': 'Deze cookies zijn essentieel voor de werking van de Site (beveiliging, weergave, taal, enz.). Ze kunnen niet worden uitgeschakeld via de toestemmingsbanner.',
      'privacy.cookies.analytics.title': '7.2. Analytische cookies (Google Analytics)',
      'privacy.cookies.analytics.desc': 'Onder voorbehoud van uw toestemming kunnen analytische cookies worden geplaatst om het verkeer op de Site te analyseren en de inhoud en ergonomie te verbeteren. Deze cookies worden alleen geactiveerd na acceptatie via de cookiebanner.',
      'privacy.cookies.consent.title': '7.3. Toestemmingsbeheer',
      'privacy.cookies.consent.desc': 'Bij uw eerste bezoek kunt u via een banner niet-essentiële cookies accepteren of weigeren, en uw voorkeuren later wijzigen. U kunt ook uw browser configureren om bepaalde cookies te blokkeren, maar dit kan bepaalde functionaliteiten beïnvloeden.',
      'privacy.confidentiality.title': '8. Vertrouwelijkheid in het kader van MSP-diensten',
      'privacy.confidentiality.content1': 'Tekio verbindt zich ertoe alle informatie, gegevens en configuraties waartoe zij toegang heeft in het kader van haar diensten als strikt vertrouwelijk te behandelen: infrastructuren, systemen en technische omgevingen, loggegevens, back-ups, configuraties, commerciële of strategische informatie van klanten.',
      'privacy.confidentiality.content2': 'Behoudens schriftelijke toestemming van de klant of wettelijke verplichting, worden deze gegevens niet bekendgemaakt noch gebruikt voor andere doeleinden dan de uitvoering van de overeengekomen diensten. Tekio zorgt er ook voor dat haar onderaannemers en partners onderworpen zijn aan gelijkwaardige vertrouwelijkheidsverplichtingen.',
      'privacy.rights.title': '9. Uw rechten',
      'privacy.rights.intro': 'Overeenkomstig Verordening (EU) 2016/679 (AVG) beschikt u over de volgende rechten:',
      'privacy.rights.item1': 'Recht op toegang tot uw gegevens',
      'privacy.rights.item2': 'Recht op rectificatie',
      'privacy.rights.item3': 'Recht op wissing (binnen de wettelijke grenzen)',
      'privacy.rights.item4': 'Recht op beperking van de verwerking',
      'privacy.rights.item5': 'Recht van bezwaar, met name in geval van prospectie',
      'privacy.rights.item6': 'Recht op gegevensoverdraagbaarheid (in bepaalde gevallen)',
      'privacy.rights.contact': 'Persoonsgegevens',
      'privacy.rights.identity': 'Een identiteitsbewijs kan worden gevraagd in geval van redelijke twijfel.',
      'privacy.complaint.title': '10. Klacht bij de toezichthoudende autoriteit',
      'privacy.complaint.intro': 'Als u van mening bent dat uw rechten niet worden gerespecteerd, kunt u een klacht indienen bij:',
      'privacy.updates.title': '11. Bijwerking van het beleid',
      'privacy.updates.content': 'Dit Privacybeleid kan worden bijgewerkt om rekening te houden met de evolutie van de diensten, de wetgeving of de technologie. De geldende versie is die gepubliceerd op de Site op de datum van raadpleging.',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.pricing': 'Pricing',
    'nav.method': 'Method & AI',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.audit': 'Free audit',
    
    // Hero
    'hero.title': 'Managed IT.',
    'hero.title2': 'Modern. Efficient.',
    'hero.subtitle': 'Tekio simplifies and centralizes your IT. Simple, clear, hassle-free.',
    'hero.cta1': 'Free audit',
    'hero.cta2': 'Talk to an expert',
    
    // Why Tekio
    'why.title': 'Why Tekio?',
    'why.subtitle': 'A modern approach to IT management for SMEs.',
    'why.support.title': 'Fast support',
    'why.support.desc': 'Response within 15 minutes. Your team never stays stuck.',
    'why.security.title': '24/7 Security',
    'why.security.desc': 'Continuous monitoring and proactive protection of your infrastructure.',
    'why.automation.title': 'Automation & AI',
    'why.automation.desc': 'Artificial intelligence at the service of your productivity.',
    
    // Services
    'services.title': 'Our services',
    'services.subtitle': 'Everything your business needs, centralized.',
    'services.support.title': 'Support & Helpdesk',
    'services.support.desc': 'Responsive technical support for your teams.',
    'services.cloud.title': 'Microsoft 365 & Cloud',
    'services.cloud.desc': 'Migration, configuration and management of your cloud tools.',
    'services.security.title': 'Security & Backup',
    'services.security.desc': 'Advanced protection and backup of your data.',
    'services.telecom.title': 'Telecom & VoIP',
    'services.telecom.desc': 'Modern and flexible communication solutions.',
    'services.projects.title': 'Projects & Migrations',
    'services.projects.desc': 'Support for your transformation projects.',
    
    // Technology
    'tech.title': 'Our technology',
    'tech.subtitle': 'Modern tools for efficient IT.',
    'tech.ai.title': 'Integrated AI',
    'tech.ai.desc': 'Intelligent incident resolution.',
    'tech.automation.title': 'Automations',
    'tech.automation.desc': 'Optimized processes and automated tasks.',
    'tech.dashboard.title': 'Dashboards',
    'tech.dashboard.desc': 'Complete visibility of your infrastructure.',
    'tech.reporting.title': 'Clear reporting',
    'tech.reporting.desc': 'Detailed and understandable monthly reports.',
    
    // Pricing
    'pricing.title': 'Our MSP plans',
    'pricing.subtitle': 'Plans tailored to your needs.',
    'pricing.setup': 'Free setup with 12-month contract',
    'pricing.per.user': '/user/month',
    'pricing.cta': 'Get started',
    'pricing.popular': 'Popular',
    'pricing.bronze.name': 'Bronze',
    'pricing.silver.name': 'Silver',
    'pricing.gold.name': 'Gold',
    'pricing.bronze.price': '€29',
    'pricing.silver.price': '€49',
    'pricing.gold.price': '€79',
    'pricing.feature.support': 'Helpdesk support',
    'pricing.feature.monitoring': 'Monitoring',
    'pricing.feature.backup': 'Cloud backup',
    'pricing.feature.security': 'Advanced security',
    'pricing.feature.m365': 'Microsoft 365 management',
    'pricing.feature.voip': 'VoIP included',
    'pricing.feature.ai': 'AI & automation',
    'pricing.feature.dedicated': 'Dedicated engineer',
    
    // CTA Final
    'cta.title': 'Take your IT to the next level.',
    'cta.subtitle': 'Contact us for a free audit of your infrastructure.',
    'cta.button': 'Request an audit',
    
    // Footer
    'footer.tagline': 'Managed IT. Modern. Efficient.',
    'footer.rights': 'All rights reserved.',
    'footer.company': 'Company',
    'footer.legal': 'Legal notice',
    'footer.privacy': 'Privacy',
    
    // About
    'about.title': 'About Tekio',
    'about.mission.title': 'Our mission',
    'about.mission.desc': 'Simplify IT for SMEs so they can focus on their core business.',
    'about.vision.title': 'Our vision',
    'about.vision.desc': 'Become the reference MSP for micro-SMEs through automation and AI.',
    'about.founder.title': 'Founder',
    'about.founder.name': 'Jawade El Hadouchi',
    'about.founder.desc': 'Over 15 years of experience in IT and infrastructure.',
    'about.values.title': 'Our values',
    'about.values.simple': 'Simple',
    'about.values.clear': 'Clear',
    'about.values.efficient': 'Efficient',
    
    // Contact
    'contact.title': 'Contact us',
    'contact.subtitle': 'A question? A project? Let\'s talk.',
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.company': 'Company',
    'contact.message': 'Message',
    'contact.send': 'Send',
    'contact.info.title': 'Contact details',
    'contact.info.address': 'Brussels, Belgium',
    
    // Audit
    'audit.title': 'Free IT audit',
    'audit.subtitle': 'Discover the improvement areas of your infrastructure.',
    'audit.benefit1': 'Complete analysis of your IT assets',
    'audit.benefit2': 'Risk identification',
    'audit.benefit3': 'Personalized recommendations',
    'audit.benefit4': 'Detailed report included',
    'audit.cta': 'Request my audit',
    
    // Method
    'method.title': 'Our method',
    'method.subtitle': 'A structured and innovative approach.',
    'method.itil.title': 'ITIL',
    'method.itil.desc': 'Processes based on ITIL best practices.',
    'method.itil.details': 'Incident, change and problem management according to international standards.',
    'method.automation.title': 'Automation',
    'method.automation.desc': 'Automated repetitive tasks for more efficiency.',
    'method.automation.details': 'Automated scripts, deployments without intervention, preventive maintenance.',
    'method.ai.title': 'Artificial intelligence',
    'method.ai.desc': 'AI for proactive detection and resolution of incidents.',
    'method.ai.details': 'Predictive analysis, automatic resolution of recurring incidents, intelligent chatbot.',
    'method.ai.badge': 'Artificial Intelligence',
    'method.ai.hero.title': 'AI at the service of your productivity',
    'method.ai.hero.desc': 'Our platform integrates artificial intelligence capabilities to anticipate problems, automate repetitive tasks and offer you ever faster and more relevant support.',
    'method.ai.hero.cta': 'Discover our AI capabilities',
    'method.reporting.title': 'Reporting',
    'method.reporting.desc': 'Total visibility with clear monthly reports.',
    'method.reporting.details': 'Real-time dashboards, detailed monthly reports, customized KPIs.',
    
    // Services Details
    'services.detail.support.1': 'Response within 15 minutes',
    'services.detail.support.2': 'Multi-channel support (phone, email, chat)',
    'services.detail.support.3': '24/7 accessible knowledge base',
    'services.detail.support.4': 'Real-time ticket tracking',
    'services.detail.cloud.1': 'Complete Office 365 migration',
    'services.detail.cloud.2': 'Configuration and optimization',
    'services.detail.cloud.3': 'User training',
    'services.detail.cloud.4': 'License management',
    'services.detail.security.1': 'Managed antivirus and anti-malware',
    'services.detail.security.2': 'Automated cloud backup',
    'services.detail.security.3': 'Monthly recovery test',
    'services.detail.security.4': '24/7 threat monitoring',
    'services.detail.telecom.1': 'Professional VoIP telephony',
    'services.detail.telecom.2': 'Teams / Microsoft integration',
    'services.detail.telecom.3': 'Local and international numbers',
    'services.detail.telecom.4': 'Guaranteed portability',
    'services.detail.projects.1': 'Complete infrastructure migration',
    'services.detail.projects.2': 'Deployment of new sites',
    'services.detail.projects.3': 'Audit and technical advice',
    'services.detail.projects.4': 'Dedicated project management',
    'services.cta.discover': 'Discover all our services',
    'services.cta.learn': 'Learn more',
    
    // Audit Page
    'audit.free': '100% Free',
    'audit.includes.title': 'What our audit includes',
    'audit.process.title': 'How does it work?',
    'audit.process.step1': 'Fill out the form',
    'audit.process.step2': 'We schedule a 30-min call',
    'audit.process.step3': 'Receive your personalized report',
    'audit.form.title': 'Request my free audit',
    'audit.form.firstName': 'First name',
    'audit.form.lastName': 'Last name',
    'audit.form.email': 'Professional email',
    'audit.form.company': 'Company',
    'audit.form.phone': 'Phone',
    'audit.form.employees': 'Number of employees',
    'audit.form.needs': 'Your main needs',
    'audit.form.placeholder.firstName': 'John',
    'audit.form.placeholder.lastName': 'Doe',
    'audit.form.placeholder.email': 'john@company.be',
    'audit.form.placeholder.company': 'Your company name',
    'audit.form.placeholder.phone': '+32 XXX XX XX XX',
    'audit.form.placeholder.needs': 'Briefly describe your current IT situation...',
    'audit.form.select.placeholder': 'Select',
    'audit.form.submit.sending': 'Sending...',
    'audit.form.privacy': 'By submitting this form, you agree to be contacted by Tekio.',
    'audit.toast.success.title': 'Request sent!',
    'audit.toast.success.desc': 'We will contact you within 24h to schedule your audit.',
    
    // Pricing Page
    'pricing.plan.bronze.desc': 'For small teams getting started',
    'pricing.plan.silver.desc': 'The perfect balance for SMEs',
    'pricing.plan.gold.desc': 'All-inclusive premium service',
    'pricing.questions.title': 'Questions about our offers?',
    'pricing.questions.desc': 'Every business is unique. Contact us for a personalized offer tailored to your needs.',
    'pricing.dialog.title': 'Request a quote',
    'pricing.dialog.desc': 'Fill in this form and we will contact you with a personalized offer.',
    'pricing.dialog.name': 'Name',
    'pricing.dialog.email': 'Email',
    'pricing.dialog.company': 'Company',
    'pricing.dialog.employees': 'Number of users',
    'pricing.dialog.message': 'Message (optional)',
    'pricing.dialog.placeholder.name': 'Your name',
    'pricing.dialog.placeholder.email': 'you@company.be',
    'pricing.dialog.placeholder.company': 'Your company name',
    'pricing.dialog.placeholder.message': 'Specific needs?',
    'pricing.dialog.submit': 'Send my request',
    'pricing.dialog.submit.sending': 'Sending...',
    'pricing.toast.success.title': 'Request sent!',
    'pricing.toast.success.desc': 'We will contact you shortly with a personalized offer.',
    'pricing.interest.prefix': 'Interested plan:',
    
    // About Page
    'about.hero.tagline': 'A modern MSP based in Brussels, dedicated to micro-SMEs.',
    'about.founder.quote': 'My goal is simple: offer SMEs the same tools and the same level of service as large companies, but at an affordable price and with a human approach.',
    'about.cta.ready': 'Ready to simplify your IT?',
    'about.cta.discuss': 'Let\'s talk about your project',
    
    // Contact Page
    'contact.form.placeholder.name': 'John Doe',
    'contact.form.placeholder.email': 'john@company.be',
    'contact.form.placeholder.company': 'Your company',
    'contact.form.placeholder.message': 'How can we help you?',
    'contact.form.submit.sending': 'Sending...',
    'contact.info.address.label': 'Address',
    'contact.info.email.label': 'Email',
    'contact.info.phone.label': 'WhatsApp Business',
      'contact.toast.success.title': 'Message sent!',
      'contact.toast.success.desc': 'We will respond as soon as possible.',

      // Admin - Leads List
      'admin.leads.title': 'Lead Management',
      'admin.leads.subtitle': 'Tekio Admin',
      'admin.leads.back': 'Back to site',
      'admin.leads.filter': 'Filter by status',
      'admin.leads.reset': 'Reset',
      'admin.leads.loading': 'Loading...',
      'admin.leads.error': 'Error loading leads',
      'admin.leads.empty': 'No leads found',
      'admin.leads.all': 'All leads',
      'admin.leads.table.date': 'Date',
      'admin.leads.table.company': 'Company',
      'admin.leads.table.contact': 'Contact',
      'admin.leads.table.email': 'Email',
      'admin.leads.table.users': 'Users',
      'admin.leads.table.source': 'Source',
      'admin.leads.table.status': 'Status',
      'admin.leads.table.actions': 'Actions',

      // Admin - Lead Detail
      'admin.lead.back': 'Back',
      'admin.lead.id': 'Lead #',
      'admin.lead.info': 'Lead information',
      'admin.lead.company': 'Company',
      'admin.lead.contact': 'Contact',
      'admin.lead.email': 'Email',
      'admin.lead.phone': 'Phone',
      'admin.lead.language': 'Language',
      'admin.lead.users': 'Number of users',
      'admin.lead.created': 'Creation date',
      'admin.lead.source': 'Source',
      'admin.lead.message': 'Message',
      'admin.lead.ai.title': 'AI suggested reply',
      'admin.lead.ai.generate': 'Generate reply',
      'admin.lead.ai.generating': 'Generating...',
      'admin.lead.ai.copy': 'Copy reply',
      'admin.lead.ai.copied': 'Copied!',
      'admin.lead.ai.empty': 'Click "Generate reply" to get a personalized email suggestion.',
      'admin.lead.status.title': 'Status',
      'admin.lead.status.new': 'New',
      'admin.lead.status.contacted': 'Contacted',
      'admin.lead.status.proposal': 'Proposal',
      'admin.lead.status.won': 'Won',
      'admin.lead.status.lost': 'Lost',
      'admin.lead.notes.title': 'Internal notes',
      'admin.lead.notes.placeholder': 'Add your notes here...',
      'admin.lead.notes.save': 'Save',
      'admin.lead.notes.saving': 'Saving...',
      'admin.lead.actions.title': 'Quick actions',
      'admin.lead.actions.email': 'Send email',
      'admin.lead.actions.call': 'Call',
      'admin.lead.loading': 'Loading...',
      'admin.lead.notfound': 'Lead not found',
      'admin.lead.notfound.back': 'Back to list',
      'admin.lead.toast.copied.title': 'Copied!',
      'admin.lead.toast.copied.desc': 'The reply has been copied to the clipboard.',
      
      // Admin - Sources
      'admin.source.home': 'Home',
      'admin.source.audit_page': 'Audit Page',
      'admin.source.contact_page': 'Contact Page',
      'admin.source.pricing_page': 'Pricing Page',
      
      // Admin - Languages
      'admin.lang.FR': 'French',
      'admin.lang.NL': 'Dutch',
      'admin.lang.EN': 'English',

      // Legal Page
      'legal.title': 'Legal Notice',
      'legal.editor.title': '1. Website Publisher',
      'legal.editor.intro': 'The website https://www.tekio.be (hereinafter "the Site") is published by:',
      'legal.editor.address': 'Registered office',
      'legal.editor.bce': 'Company number (BCE)',
      'legal.editor.vat': 'VAT number',
      'legal.editor.email': 'Contact email',
      'legal.publisher.title': '2. Publication Manager',
      'legal.publisher.intro': 'The publication manager is:',
      'legal.publisher.role': 'as manager of HDC-AZG SRL',
      'legal.host.title': '3. Hosting Provider',
      'legal.host.intro': 'The Site is hosted by:',
      'legal.purpose.title': '4. Website Purpose',
      'legal.purpose.intro': 'The purpose of the Site is to present the services of Tekio, a brand operated by HDC-AZG SRL, notably services including:',
      'legal.purpose.service1': 'Managed Services Provider (MSP) and IT management',
      'legal.purpose.service2': 'Infrastructure management, support and monitoring',
      'legal.purpose.service3': 'Automation, cybersecurity and digitalization for businesses',
      'legal.purpose.disclaimer': 'The information published on the Site is provided for informational purposes and may be modified at any time.',
      'legal.ip.title': '5. Intellectual Property',
      'legal.ip.content1': 'All content on the Site (texts, images, logos, graphic elements, videos, icons, structure, code) is the exclusive property of HDC-AZG SRL or used with permission from third parties.',
      'legal.ip.content2': 'Any reproduction, representation, adaptation or distribution, in whole or in part, by any means whatsoever, without prior written authorization, is prohibited and may constitute infringement.',
      'legal.links.title': '6. Hyperlinks',
      'legal.links.content1': 'The Site may contain links to other websites. HDC-AZG SRL has no control over these sites and cannot be held responsible for their content, operation or legality.',
      'legal.links.content2': 'Creating links to the Site is permitted subject to:',
      'legal.links.condition1': 'not damaging the image or reputation of Tekio or HDC-AZG SRL',
      'legal.links.condition2': 'not falsely suggesting a partnership or sponsorship',
      'legal.links.content3': 'HDC-AZG SRL reserves the right to request the removal of any link it deems inappropriate.',
      'legal.liability.title': '7. Liability',
      'legal.liability.content1': 'HDC-AZG SRL uses reasonable means to ensure the accuracy and updating of information on the Site. However:',
      'legal.liability.point1': 'no guarantee is given as to the completeness or timeliness of the information',
      'legal.liability.point2': 'the publisher cannot be held liable for direct or indirect damages resulting from the use of the Site or the inability to access it',
      'legal.liability.point3': 'the user remains responsible for protecting their equipment and data',
      'legal.liability.content2': 'This limitation of liability does not apply in cases of gross negligence, fraud or mandatory legal provisions to the contrary.',
      'legal.jurisdiction.title': '8. Applicable Law and Jurisdiction',
      'legal.jurisdiction.content1': 'These Legal Notices are governed by Belgian law.',
      'legal.jurisdiction.content2': 'In the absence of amicable resolution, any dispute relating to the use of the Site shall be submitted to the competent courts of the Brussels judicial district, without prejudice to mandatory jurisdiction rules.',

      // Privacy Page
      'privacy.title': 'Privacy Policy & Cookies',
      'privacy.controller.title': '1. Data Controller',
      'privacy.controller.intro': 'The data controller for personal data is:',
      'privacy.controller.email': 'Contact email for data protection',
      'privacy.controller.dpo': 'No Data Protection Officer (DPO) is formally designated. Any privacy-related questions can be addressed to this email.',
      'privacy.data.title': '2. Data Collected',
      'privacy.data.user.title': '2.1. Data Provided by the User',
      'privacy.data.user.intro': 'Through the contact form or exchanges with Tekio, the following data may be collected:',
      'privacy.data.user.item1': 'First and last name',
      'privacy.data.user.item2': 'Email address',
      'privacy.data.user.item3': 'Phone number',
      'privacy.data.user.item4': 'Company name and position',
      'privacy.data.user.item5': 'Content of the message or request',
      'privacy.data.user.item6': 'Information necessary for preparing a quote or contract',
      'privacy.data.auto.title': '2.2. Automatically Collected Data',
      'privacy.data.auto.intro': 'When browsing the Site, certain technical data is automatically collected:',
      'privacy.data.auto.item1': 'IP address',
      'privacy.data.auto.item2': 'Browser type and operating system',
      'privacy.data.auto.item3': 'Pages viewed, visit duration',
      'privacy.data.auto.item4': 'Technical log data',
      'privacy.data.auto.item5': 'Cookies and trackers (see section 7)',
      'privacy.data.msp.title': '2.3. Data in the Context of MSP Services',
      'privacy.data.msp.intro': 'In the context of providing IT/MSP services, Tekio may process the following data on behalf of its clients:',
      'privacy.data.msp.item1': 'Technical configuration information',
      'privacy.data.msp.item2': 'System logs and event journals',
      'privacy.data.msp.item3': 'Support and incident-related data',
      'privacy.data.msp.item4': 'Billing and technical contact identification data',
      'privacy.data.msp.disclaimer': 'This data is processed in accordance with contracts concluded with each client and the client\'s written instructions when Tekio acts as a processor.',
      'privacy.purposes.title': '3. Purposes and Legal Bases',
      'privacy.purposes.intro': 'Data is processed for the following purposes:',
      'privacy.purposes.purpose1.title': 'Management of contact and quote requests',
      'privacy.purposes.purpose1.desc': 'Reception and response to messages sent via the Site or by email',
      'privacy.purposes.purpose1.basis': 'Legal basis: pre-contractual measures and legitimate interest',
      'privacy.purposes.purpose2.title': 'Customer relationship management and MSP service execution',
      'privacy.purposes.purpose2.desc': 'Implementation, delivery and monitoring of services. Billing, support, maintenance.',
      'privacy.purposes.purpose2.basis': 'Legal basis: contract execution',
      'privacy.purposes.purpose3.title': 'Reasonable B2B prospecting and communication',
      'privacy.purposes.purpose3.desc': 'Sending information related to Tekio services to professional contacts',
      'privacy.purposes.purpose3.basis': 'Legal basis: legitimate interest, in compliance with the applicable B2B prospecting framework',
      'privacy.purposes.purpose4.title': 'Site improvement and audience statistics',
      'privacy.purposes.purpose4.desc': 'Traffic analysis via Google Analytics (after consent)',
      'privacy.purposes.purpose4.basis': 'Legal basis: consent for analytics cookies',
      'privacy.purposes.purpose5.title': 'Compliance with legal obligations',
      'privacy.purposes.purpose5.desc': 'Retention of accounting documents, tax and legal obligations',
      'privacy.purposes.purpose5.basis': 'Legal basis: applicable legal obligations',
      'privacy.recipients.title': '4. Data Recipients',
      'privacy.recipients.intro': 'Data may be accessible to:',
      'privacy.recipients.item1': 'HDC-AZG SRL personnel authorized to process it',
      'privacy.recipients.item2': 'Technical service providers acting as processors (Hosting: OVH, Analytics tool: Google Analytics, CRM: HubSpot)',
      'privacy.recipients.disclaimer': 'These processors are contractually required to maintain confidentiality and implement appropriate security measures. Data is not resold to third parties.',
      'privacy.transfers.title': '5. Data Transfers Outside the EU',
      'privacy.transfers.intro': 'Some service providers (e.g., Google, HubSpot) may be located outside the European Economic Area (EEA). In such cases, Tekio ensures that appropriate safeguards are in place, such as:',
      'privacy.transfers.item1': 'standard contractual clauses adopted by the European Commission',
      'privacy.transfers.item2': 'additional security and confidentiality measures',
      'privacy.transfers.item3': 'or use of service providers benefiting from a recognized adequate level of protection',
      'privacy.retention.title': '6. Retention Period',
      'privacy.retention.intro': 'Data is retained for limited periods:',
      'privacy.retention.item1': 'Contact data (prospects): up to 3 years after the last significant contact, unless objection',
      'privacy.retention.item2': 'Customer data and contractual documents: during the contract term, then according to legal obligations (notably accounting)',
      'privacy.retention.item3': 'Technical logs and security data: generally between 6 months and 1 year, unless specific need',
      'privacy.retention.item4': 'Cookies: variable duration depending on their nature (see section 7)',
      'privacy.retention.disclaimer': 'At the end of these periods, data is deleted, anonymized or archived when required by law.',
      'privacy.cookies.title': '7. Cookies',
      'privacy.cookies.intro': 'The Site uses cookies and similar technologies:',
      'privacy.cookies.essential.title': '7.1. Strictly Necessary Cookies',
      'privacy.cookies.essential.desc': 'These cookies are essential for the Site to function (security, display, language, etc.). They cannot be disabled via the consent banner.',
      'privacy.cookies.analytics.title': '7.2. Analytics Cookies (Google Analytics)',
      'privacy.cookies.analytics.desc': 'Subject to your consent, analytics cookies may be placed to analyze Site traffic and improve content and usability. These cookies are only activated after acceptance via the cookie banner.',
      'privacy.cookies.consent.title': '7.3. Consent Management',
      'privacy.cookies.consent.desc': 'On your first visit, a banner allows you to accept or refuse non-essential cookies and modify your preferences later. You can also configure your browser to block certain cookies, but this may affect some features.',
      'privacy.confidentiality.title': '8. Confidentiality in the Context of MSP Services',
      'privacy.confidentiality.content1': 'Tekio commits to treating as strictly confidential all information, data and configurations it accesses in the context of its services: infrastructures, systems and technical environments, log data, backups, configurations, commercial or strategic client information.',
      'privacy.confidentiality.content2': 'Unless written client agreement or legal obligation, this information is neither disclosed nor used for purposes other than the execution of agreed services. Tekio also ensures that its subcontractors and partners are subject to equivalent confidentiality obligations.',
      'privacy.rights.title': '9. Your Rights',
      'privacy.rights.intro': 'In accordance with Regulation (EU) 2016/679 (GDPR), you have the following rights:',
      'privacy.rights.item1': 'Right of access to your data',
      'privacy.rights.item2': 'Right to rectification',
      'privacy.rights.item3': 'Right to erasure (within legal limits)',
      'privacy.rights.item4': 'Right to restriction of processing',
      'privacy.rights.item5': 'Right to object, particularly for prospecting',
      'privacy.rights.item6': 'Right to data portability (in certain cases)',
      'privacy.rights.contact': 'Personal Data',
      'privacy.rights.identity': 'Proof of identity may be requested in case of reasonable doubt.',
      'privacy.complaint.title': '10. Complaint to the Supervisory Authority',
      'privacy.complaint.intro': 'If you believe your rights are not being respected, you can file a complaint with:',
      'privacy.updates.title': '11. Policy Updates',
      'privacy.updates.content': 'This Privacy Policy may be updated to reflect changes in services, legislation or technology. The current version is the one published on the Site at the date of consultation.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
